# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversation_manager.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63onversation_manager.proto\x12\x14\x63onversation_manager\x1a\x1bgoogle/protobuf/empty.proto\":\n\x18\x43omplaint_serviceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\";\n\x19\x43omplaint_serviceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\"l\n\x16\x43reateComplaintRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07product\x18\x03 \x01(\t\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x0f\n\x07\x65motion\x18\x05 \x01(\t\"P\n\x17\x43reateComplaintResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0c\x63omplaint_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2\xb2\x02\n\x11\x43omplaint_service\x12n\n\x0b\x44oSomething\x12..conversation_manager.Complaint_serviceRequest\x1a/.conversation_manager.Complaint_serviceResponse\x12n\n\x0f\x43reateComplaint\x12,.conversation_manager.CreateComplaintRequest\x1a-.conversation_manager.CreateComplaintResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBUZSgithub.com/milkyhoop/template-service-golang/internal/delivery/pb/template;templateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZSgithub.com/milkyhoop/template-service-golang/internal/delivery/pb/template;template'
  _globals['_COMPLAINT_SERVICEREQUEST']._serialized_start=81
  _globals['_COMPLAINT_SERVICEREQUEST']._serialized_end=139
  _globals['_COMPLAINT_SERVICERESPONSE']._serialized_start=141
  _globals['_COMPLAINT_SERVICERESPONSE']._serialized_end=200
  _globals['_CREATECOMPLAINTREQUEST']._serialized_start=202
  _globals['_CREATECOMPLAINTREQUEST']._serialized_end=310
  _globals['_CREATECOMPLAINTRESPONSE']._serialized_start=312
  _globals['_CREATECOMPLAINTRESPONSE']._serialized_end=392
  _globals['_COMPLAINT_SERVICE']._serialized_start=395
  _globals['_COMPLAINT_SERVICE']._serialized_end=701
# @@protoc_insertion_point(module_scope)
