# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import accounting_service_pb2 as accounting__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in accounting_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AccountingServiceStub(object):
    """============================================
    ACCOUNTING SERVICE
    ============================================
    Financial accounting & SAK EMKM compliance engine
    - Auto-generate journal entries (double-entry bookkeeping)
    - Chart of accounts (BaganAkun) management
    - Automatic CoA mapping from transaction data
    - Double-entry validation (Debit = Credit)

    ==========================================
    JOURNAL ENTRY OPERATIONS
    ==========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTransaction = channel.unary_unary(
                '/accounting_service.AccountingService/ProcessTransaction',
                request_serializer=accounting__service__pb2.ProcessTransactionRequest.SerializeToString,
                response_deserializer=accounting__service__pb2.ProcessTransactionResponse.FromString,
                _registered_method=True)
        self.GetJournalEntry = channel.unary_unary(
                '/accounting_service.AccountingService/GetJournalEntry',
                request_serializer=accounting__service__pb2.GetJournalEntryRequest.SerializeToString,
                response_deserializer=accounting__service__pb2.GetJournalEntryResponse.FromString,
                _registered_method=True)
        self.GetJournalEntriesByPeriod = channel.unary_unary(
                '/accounting_service.AccountingService/GetJournalEntriesByPeriod',
                request_serializer=accounting__service__pb2.GetJournalEntriesByPeriodRequest.SerializeToString,
                response_deserializer=accounting__service__pb2.GetJournalEntriesByPeriodResponse.FromString,
                _registered_method=True)
        self.CreateAccount = channel.unary_unary(
                '/accounting_service.AccountingService/CreateAccount',
                request_serializer=accounting__service__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=accounting__service__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.GetAccount = channel.unary_unary(
                '/accounting_service.AccountingService/GetAccount',
                request_serializer=accounting__service__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=accounting__service__pb2.GetAccountResponse.FromString,
                _registered_method=True)
        self.ListAccounts = channel.unary_unary(
                '/accounting_service.AccountingService/ListAccounts',
                request_serializer=accounting__service__pb2.ListAccountsRequest.SerializeToString,
                response_deserializer=accounting__service__pb2.ListAccountsResponse.FromString,
                _registered_method=True)
        self.UpdateAccount = channel.unary_unary(
                '/accounting_service.AccountingService/UpdateAccount',
                request_serializer=accounting__service__pb2.UpdateAccountRequest.SerializeToString,
                response_deserializer=accounting__service__pb2.UpdateAccountResponse.FromString,
                _registered_method=True)
        self.DeactivateAccount = channel.unary_unary(
                '/accounting_service.AccountingService/DeactivateAccount',
                request_serializer=accounting__service__pb2.DeactivateAccountRequest.SerializeToString,
                response_deserializer=accounting__service__pb2.DeactivateAccountResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/accounting_service.AccountingService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=accounting__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class AccountingServiceServicer(object):
    """============================================
    ACCOUNTING SERVICE
    ============================================
    Financial accounting & SAK EMKM compliance engine
    - Auto-generate journal entries (double-entry bookkeeping)
    - Chart of accounts (BaganAkun) management
    - Automatic CoA mapping from transaction data
    - Double-entry validation (Debit = Credit)

    ==========================================
    JOURNAL ENTRY OPERATIONS
    ==========================================
    """

    def ProcessTransaction(self, request, context):
        """Process transaction and auto-generate journal entries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJournalEntry(self, request, context):
        """Get journal entries for a transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJournalEntriesByPeriod(self, request, context):
        """Get journal entries for a period (for reporting)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccount(self, request, context):
        """==========================================
        CHART OF ACCOUNTS OPERATIONS
        ==========================================

        Create new account in chart of accounts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccount(self, request, context):
        """Get account details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccounts(self, request, context):
        """List all accounts for tenant
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccount(self, request, context):
        """Update account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateAccount(self, request, context):
        """Deactivate account (soft delete)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """==========================================
        UTILITY OPERATIONS
        ==========================================

        Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTransaction,
                    request_deserializer=accounting__service__pb2.ProcessTransactionRequest.FromString,
                    response_serializer=accounting__service__pb2.ProcessTransactionResponse.SerializeToString,
            ),
            'GetJournalEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJournalEntry,
                    request_deserializer=accounting__service__pb2.GetJournalEntryRequest.FromString,
                    response_serializer=accounting__service__pb2.GetJournalEntryResponse.SerializeToString,
            ),
            'GetJournalEntriesByPeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJournalEntriesByPeriod,
                    request_deserializer=accounting__service__pb2.GetJournalEntriesByPeriodRequest.FromString,
                    response_serializer=accounting__service__pb2.GetJournalEntriesByPeriodResponse.SerializeToString,
            ),
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=accounting__service__pb2.CreateAccountRequest.FromString,
                    response_serializer=accounting__service__pb2.CreateAccountResponse.SerializeToString,
            ),
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=accounting__service__pb2.GetAccountRequest.FromString,
                    response_serializer=accounting__service__pb2.GetAccountResponse.SerializeToString,
            ),
            'ListAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccounts,
                    request_deserializer=accounting__service__pb2.ListAccountsRequest.FromString,
                    response_serializer=accounting__service__pb2.ListAccountsResponse.SerializeToString,
            ),
            'UpdateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccount,
                    request_deserializer=accounting__service__pb2.UpdateAccountRequest.FromString,
                    response_serializer=accounting__service__pb2.UpdateAccountResponse.SerializeToString,
            ),
            'DeactivateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateAccount,
                    request_deserializer=accounting__service__pb2.DeactivateAccountRequest.FromString,
                    response_serializer=accounting__service__pb2.DeactivateAccountResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=accounting__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accounting_service.AccountingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccountingService(object):
    """============================================
    ACCOUNTING SERVICE
    ============================================
    Financial accounting & SAK EMKM compliance engine
    - Auto-generate journal entries (double-entry bookkeeping)
    - Chart of accounts (BaganAkun) management
    - Automatic CoA mapping from transaction data
    - Double-entry validation (Debit = Credit)

    ==========================================
    JOURNAL ENTRY OPERATIONS
    ==========================================
    """

    @staticmethod
    def ProcessTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/ProcessTransaction',
            accounting__service__pb2.ProcessTransactionRequest.SerializeToString,
            accounting__service__pb2.ProcessTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJournalEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/GetJournalEntry',
            accounting__service__pb2.GetJournalEntryRequest.SerializeToString,
            accounting__service__pb2.GetJournalEntryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJournalEntriesByPeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/GetJournalEntriesByPeriod',
            accounting__service__pb2.GetJournalEntriesByPeriodRequest.SerializeToString,
            accounting__service__pb2.GetJournalEntriesByPeriodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/CreateAccount',
            accounting__service__pb2.CreateAccountRequest.SerializeToString,
            accounting__service__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/GetAccount',
            accounting__service__pb2.GetAccountRequest.SerializeToString,
            accounting__service__pb2.GetAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/ListAccounts',
            accounting__service__pb2.ListAccountsRequest.SerializeToString,
            accounting__service__pb2.ListAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/UpdateAccount',
            accounting__service__pb2.UpdateAccountRequest.SerializeToString,
            accounting__service__pb2.UpdateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/DeactivateAccount',
            accounting__service__pb2.DeactivateAccountRequest.SerializeToString,
            accounting__service__pb2.DeactivateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accounting_service.AccountingService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            accounting__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
