# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import business_parser_pb2 as business__parser__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in business_parser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class BusinessParserStub(object):
    """============================================
    BusinessParser Service
    Purpose: Intent classification and entity extraction for tenant queries
    Scope: Financial reports, analytics, inventory, accounting queries
    Architecture: Called by tenant_orchestrator → routes to financial services
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClassifyIntent = channel.unary_unary(
                '/business_parser.BusinessParser/ClassifyIntent',
                request_serializer=business__parser__pb2.ClassifyIntentRequest.SerializeToString,
                response_deserializer=business__parser__pb2.ClassifyIntentResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/business_parser.BusinessParser/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class BusinessParserServicer(object):
    """============================================
    BusinessParser Service
    Purpose: Intent classification and entity extraction for tenant queries
    Scope: Financial reports, analytics, inventory, accounting queries
    Architecture: Called by tenant_orchestrator → routes to financial services
    ============================================

    """

    def ClassifyIntent(self, request, context):
        """Main intent classification endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusinessParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClassifyIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyIntent,
                    request_deserializer=business__parser__pb2.ClassifyIntentRequest.FromString,
                    response_serializer=business__parser__pb2.ClassifyIntentResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'business_parser.BusinessParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BusinessParser(object):
    """============================================
    BusinessParser Service
    Purpose: Intent classification and entity extraction for tenant queries
    Scope: Financial reports, analytics, inventory, accounting queries
    Architecture: Called by tenant_orchestrator → routes to financial services
    ============================================

    """

    @staticmethod
    def ClassifyIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/business_parser.BusinessParser/ClassifyIntent',
            business__parser__pb2.ClassifyIntentRequest.SerializeToString,
            business__parser__pb2.ClassifyIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/business_parser.BusinessParser/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
