# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import conversation_service_pb2 as conversation__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in conversation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ConversationServiceStub(object):
    """============================================
    CONVERSATION SERVICE - CHAT PERSISTENCE
    ============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveMessage = channel.unary_unary(
                '/conversation_service.ConversationService/SaveMessage',
                request_serializer=conversation__service__pb2.SaveMessageRequest.SerializeToString,
                response_deserializer=conversation__service__pb2.SaveMessageResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/conversation_service.ConversationService/GetChatHistory',
                request_serializer=conversation__service__pb2.GetChatHistoryRequest.SerializeToString,
                response_deserializer=conversation__service__pb2.GetChatHistoryResponse.FromString,
                _registered_method=True)
        self.GetMessagesSince = channel.unary_unary(
                '/conversation_service.ConversationService/GetMessagesSince',
                request_serializer=conversation__service__pb2.GetMessagesSinceRequest.SerializeToString,
                response_deserializer=conversation__service__pb2.GetMessagesSinceResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/conversation_service.ConversationService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ConversationServiceServicer(object):
    """============================================
    CONVERSATION SERVICE - CHAT PERSISTENCE
    ============================================
    """

    def SaveMessage(self, request, context):
        """Save a chat message with response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Get paginated chat history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessagesSince(self, request, context):
        """Get messages since a timestamp (for sync)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConversationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMessage,
                    request_deserializer=conversation__service__pb2.SaveMessageRequest.FromString,
                    response_serializer=conversation__service__pb2.SaveMessageResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=conversation__service__pb2.GetChatHistoryRequest.FromString,
                    response_serializer=conversation__service__pb2.GetChatHistoryResponse.SerializeToString,
            ),
            'GetMessagesSince': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessagesSince,
                    request_deserializer=conversation__service__pb2.GetMessagesSinceRequest.FromString,
                    response_serializer=conversation__service__pb2.GetMessagesSinceResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conversation_service.ConversationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConversationService(object):
    """============================================
    CONVERSATION SERVICE - CHAT PERSISTENCE
    ============================================
    """

    @staticmethod
    def SaveMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation_service.ConversationService/SaveMessage',
            conversation__service__pb2.SaveMessageRequest.SerializeToString,
            conversation__service__pb2.SaveMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation_service.ConversationService/GetChatHistory',
            conversation__service__pb2.GetChatHistoryRequest.SerializeToString,
            conversation__service__pb2.GetChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessagesSince(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation_service.ConversationService/GetMessagesSince',
            conversation__service__pb2.GetMessagesSinceRequest.SerializeToString,
            conversation__service__pb2.GetMessagesSinceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation_service.ConversationService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
