# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import inventory_service_pb2 as inventory__service__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventory_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class InventoryServiceStub(object):
    """========================================
    Inventory Service - Stock Management & Validation
    ========================================
    Purpose: Process inventory movements and maintain current stock ledger
    Architecture: Event-driven processor + Query service
    Port: 7040
    Dependencies: transaction_service (7020), PostgreSQL
    SAK EMKM: Persediaan (Laporan Posisi Keuangan - Aset Lancar)
    ========================================

    ========================================
    STOCK QUERIES
    ========================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStockLevel = channel.unary_unary(
                '/inventory_service.InventoryService/GetStockLevel',
                request_serializer=inventory__service__pb2.GetStockLevelRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.StockLevelResponse.FromString,
                _registered_method=True)
        self.GetStockLevelsBatch = channel.unary_unary(
                '/inventory_service.InventoryService/GetStockLevelsBatch',
                request_serializer=inventory__service__pb2.GetStockLevelsBatchRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.StockLevelsBatchResponse.FromString,
                _registered_method=True)
        self.GetLowStockAlerts = channel.unary_unary(
                '/inventory_service.InventoryService/GetLowStockAlerts',
                request_serializer=inventory__service__pb2.GetLowStockAlertsRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.LowStockAlertsResponse.FromString,
                _registered_method=True)
        self.GetStockMovementHistory = channel.unary_unary(
                '/inventory_service.InventoryService/GetStockMovementHistory',
                request_serializer=inventory__service__pb2.GetStockMovementHistoryRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.StockMovementHistoryResponse.FromString,
                _registered_method=True)
        self.GetInventoryValuation = channel.unary_unary(
                '/inventory_service.InventoryService/GetInventoryValuation',
                request_serializer=inventory__service__pb2.GetInventoryValuationRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.InventoryValuationResponse.FromString,
                _registered_method=True)
        self.ValidateStockAvailability = channel.unary_unary(
                '/inventory_service.InventoryService/ValidateStockAvailability',
                request_serializer=inventory__service__pb2.ValidateStockRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.ValidateStockResponse.FromString,
                _registered_method=True)
        self.ProcessInventoryImpact = channel.unary_unary(
                '/inventory_service.InventoryService/ProcessInventoryImpact',
                request_serializer=inventory__service__pb2.ProcessInventoryImpactRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.ProcessInventoryImpactResponse.FromString,
                _registered_method=True)
        self.AdjustStock = channel.unary_unary(
                '/inventory_service.InventoryService/AdjustStock',
                request_serializer=inventory__service__pb2.AdjustStockRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.AdjustStockResponse.FromString,
                _registered_method=True)
        self.SetMinimumStock = channel.unary_unary(
                '/inventory_service.InventoryService/SetMinimumStock',
                request_serializer=inventory__service__pb2.SetMinimumStockRequest.SerializeToString,
                response_deserializer=inventory__service__pb2.SetMinimumStockResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/inventory_service.InventoryService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=inventory__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """========================================
    Inventory Service - Stock Management & Validation
    ========================================
    Purpose: Process inventory movements and maintain current stock ledger
    Architecture: Event-driven processor + Query service
    Port: 7040
    Dependencies: transaction_service (7020), PostgreSQL
    SAK EMKM: Persediaan (Laporan Posisi Keuangan - Aset Lancar)
    ========================================

    ========================================
    STOCK QUERIES
    ========================================
    """

    def GetStockLevel(self, request, context):
        """Get current stock level for a product at specific warehouse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockLevelsBatch(self, request, context):
        """Get stock levels for multiple products (batch query)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLowStockAlerts(self, request, context):
        """Get all products with low stock (below minimum threshold)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStockMovementHistory(self, request, context):
        """Get stock movement history for a product
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInventoryValuation(self, request, context):
        """Get inventory valuation (total value for Neraca)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateStockAvailability(self, request, context):
        """========================================
        STOCK OPERATIONS
        ========================================

        Validate stock availability before creating transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessInventoryImpact(self, request, context):
        """Process inventory impact from transaction (called by transaction_service)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdjustStock(self, request, context):
        """Update stock levels manually (stock opname/adjustment)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMinimumStock(self, request, context):
        """Set minimum stock threshold for alerts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """========================================
        HEALTH CHECK
        ========================================

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStockLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockLevel,
                    request_deserializer=inventory__service__pb2.GetStockLevelRequest.FromString,
                    response_serializer=inventory__service__pb2.StockLevelResponse.SerializeToString,
            ),
            'GetStockLevelsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockLevelsBatch,
                    request_deserializer=inventory__service__pb2.GetStockLevelsBatchRequest.FromString,
                    response_serializer=inventory__service__pb2.StockLevelsBatchResponse.SerializeToString,
            ),
            'GetLowStockAlerts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLowStockAlerts,
                    request_deserializer=inventory__service__pb2.GetLowStockAlertsRequest.FromString,
                    response_serializer=inventory__service__pb2.LowStockAlertsResponse.SerializeToString,
            ),
            'GetStockMovementHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockMovementHistory,
                    request_deserializer=inventory__service__pb2.GetStockMovementHistoryRequest.FromString,
                    response_serializer=inventory__service__pb2.StockMovementHistoryResponse.SerializeToString,
            ),
            'GetInventoryValuation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInventoryValuation,
                    request_deserializer=inventory__service__pb2.GetInventoryValuationRequest.FromString,
                    response_serializer=inventory__service__pb2.InventoryValuationResponse.SerializeToString,
            ),
            'ValidateStockAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateStockAvailability,
                    request_deserializer=inventory__service__pb2.ValidateStockRequest.FromString,
                    response_serializer=inventory__service__pb2.ValidateStockResponse.SerializeToString,
            ),
            'ProcessInventoryImpact': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessInventoryImpact,
                    request_deserializer=inventory__service__pb2.ProcessInventoryImpactRequest.FromString,
                    response_serializer=inventory__service__pb2.ProcessInventoryImpactResponse.SerializeToString,
            ),
            'AdjustStock': grpc.unary_unary_rpc_method_handler(
                    servicer.AdjustStock,
                    request_deserializer=inventory__service__pb2.AdjustStockRequest.FromString,
                    response_serializer=inventory__service__pb2.AdjustStockResponse.SerializeToString,
            ),
            'SetMinimumStock': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMinimumStock,
                    request_deserializer=inventory__service__pb2.SetMinimumStockRequest.FromString,
                    response_serializer=inventory__service__pb2.SetMinimumStockResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=inventory__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory_service.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """========================================
    Inventory Service - Stock Management & Validation
    ========================================
    Purpose: Process inventory movements and maintain current stock ledger
    Architecture: Event-driven processor + Query service
    Port: 7040
    Dependencies: transaction_service (7020), PostgreSQL
    SAK EMKM: Persediaan (Laporan Posisi Keuangan - Aset Lancar)
    ========================================

    ========================================
    STOCK QUERIES
    ========================================
    """

    @staticmethod
    def GetStockLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/GetStockLevel',
            inventory__service__pb2.GetStockLevelRequest.SerializeToString,
            inventory__service__pb2.StockLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockLevelsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/GetStockLevelsBatch',
            inventory__service__pb2.GetStockLevelsBatchRequest.SerializeToString,
            inventory__service__pb2.StockLevelsBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLowStockAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/GetLowStockAlerts',
            inventory__service__pb2.GetLowStockAlertsRequest.SerializeToString,
            inventory__service__pb2.LowStockAlertsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStockMovementHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/GetStockMovementHistory',
            inventory__service__pb2.GetStockMovementHistoryRequest.SerializeToString,
            inventory__service__pb2.StockMovementHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInventoryValuation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/GetInventoryValuation',
            inventory__service__pb2.GetInventoryValuationRequest.SerializeToString,
            inventory__service__pb2.InventoryValuationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateStockAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/ValidateStockAvailability',
            inventory__service__pb2.ValidateStockRequest.SerializeToString,
            inventory__service__pb2.ValidateStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessInventoryImpact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/ProcessInventoryImpact',
            inventory__service__pb2.ProcessInventoryImpactRequest.SerializeToString,
            inventory__service__pb2.ProcessInventoryImpactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdjustStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/AdjustStock',
            inventory__service__pb2.AdjustStockRequest.SerializeToString,
            inventory__service__pb2.AdjustStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetMinimumStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/SetMinimumStock',
            inventory__service__pb2.SetMinimumStockRequest.SerializeToString,
            inventory__service__pb2.SetMinimumStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory_service.InventoryService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            inventory__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
