# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rule_engine.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rule_engine.proto\x12\x0brule_engine\"[\n\x0bRuleRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x14\n\x0crule_context\x18\x02 \x01(\t\x12\x11\n\trule_type\x18\x03 \x01(\t\x12\x10\n\x08trace_id\x18\x04 \x01(\t\"w\n\x0cRuleResponse\x12\x14\n\x0crule_matched\x18\x01 \x01(\x08\x12\x0f\n\x07rule_id\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63tion_json\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x17\n\x0f\x66\x61llback_reason\x18\x05 \x01(\t\":\n\x12TenantRulesRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x11\n\trule_type\x18\x02 \x01(\t\"A\n\x13TenantRulesResponse\x12*\n\x05rules\x18\x01 \x03(\x0b\x32\x1b.rule_engine.RuleDefinition\"\x94\x01\n\x0eRuleDefinition\x12\x0f\n\x07rule_id\x18\x01 \x01(\t\x12\x11\n\trule_yaml\x18\x02 \x01(\t\x12\x11\n\trule_type\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\x12\x11\n\tis_active\x18\x05 \x01(\x08\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\x12\x12\n\nupdated_at\x18\x07 \x01(\x03\"_\n\x12UpdateRulesRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x11\n\trule_yaml\x18\x02 \x01(\t\x12\x11\n\trule_type\x18\x03 \x01(\t\x12\x10\n\x08priority\x18\x04 \x01(\x05\"H\n\x13UpdateRulesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07rule_id\x18\x03 \x01(\t\"\x14\n\x12HealthCheckRequest\";\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t2\xd0\x02\n\nRuleEngine\x12\x43\n\x0c\x45valuateRule\x12\x18.rule_engine.RuleRequest\x1a\x19.rule_engine.RuleResponse\x12S\n\x0eGetTenantRules\x12\x1f.rule_engine.TenantRulesRequest\x1a .rule_engine.TenantRulesResponse\x12V\n\x11UpdateTenantRules\x12\x1f.rule_engine.UpdateRulesRequest\x1a .rule_engine.UpdateRulesResponse\x12P\n\x0bHealthCheck\x12\x1f.rule_engine.HealthCheckRequest\x1a .rule_engine.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rule_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RULEREQUEST']._serialized_start=34
  _globals['_RULEREQUEST']._serialized_end=125
  _globals['_RULERESPONSE']._serialized_start=127
  _globals['_RULERESPONSE']._serialized_end=246
  _globals['_TENANTRULESREQUEST']._serialized_start=248
  _globals['_TENANTRULESREQUEST']._serialized_end=306
  _globals['_TENANTRULESRESPONSE']._serialized_start=308
  _globals['_TENANTRULESRESPONSE']._serialized_end=373
  _globals['_RULEDEFINITION']._serialized_start=376
  _globals['_RULEDEFINITION']._serialized_end=524
  _globals['_UPDATERULESREQUEST']._serialized_start=526
  _globals['_UPDATERULESREQUEST']._serialized_end=621
  _globals['_UPDATERULESRESPONSE']._serialized_start=623
  _globals['_UPDATERULESRESPONSE']._serialized_end=695
  _globals['_HEALTHCHECKREQUEST']._serialized_start=697
  _globals['_HEALTHCHECKREQUEST']._serialized_end=717
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=719
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=778
  _globals['_RULEENGINE']._serialized_start=781
  _globals['_RULEENGINE']._serialized_end=1117
# @@protoc_insertion_point(module_scope)
