# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenant_orchestrator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19tenant_orchestrator.proto\x12\x13tenant_orchestrator\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x01\n\x19ProcessTenantQueryRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x1c\n\x14\x63onversation_context\x18\x05 \x01(\t\"\xab\x02\n\x1aProcessTenantQueryResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0emilky_response\x18\x02 \x01(\t\x12\x0e\n\x06intent\x18\x03 \x01(\t\x12\x15\n\rentities_json\x18\x04 \x01(\t\x12\x37\n\rservice_calls\x18\x05 \x03(\x0b\x32 .tenant_orchestrator.ServiceCall\x12\x19\n\x11total_duration_ms\x18\x06 \x01(\x05\x12\x12\n\nerror_code\x18\x07 \x01(\t\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12\x10\n\x08trace_id\x18\t \x01(\t\x12-\n\ttimestamp\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"X\n\x0bServiceCall\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t2\xca\x01\n\x12TenantOrchestrator\x12u\n\x12ProcessTenantQuery\x12..tenant_orchestrator.ProcessTenantQueryRequest\x1a/.tenant_orchestrator.ProcessTenantQueryResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tenant_orchestrator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROCESSTENANTQUERYREQUEST']._serialized_start=113
  _globals['_PROCESSTENANTQUERYREQUEST']._serialized_end=243
  _globals['_PROCESSTENANTQUERYRESPONSE']._serialized_start=246
  _globals['_PROCESSTENANTQUERYRESPONSE']._serialized_end=545
  _globals['_SERVICECALL']._serialized_start=547
  _globals['_SERVICECALL']._serialized_end=635
  _globals['_TENANTORCHESTRATOR']._serialized_start=638
  _globals['_TENANTORCHESTRATOR']._serialized_end=840
# @@protoc_insertion_point(module_scope)
