// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: tenant_parser.proto

package intentparser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IntentParserService_DoSomething_FullMethodName = "/tenant_parser.IntentParserService/DoSomething"
	IntentParserService_HealthCheck_FullMethodName = "/tenant_parser.IntentParserService/HealthCheck"
)

// IntentParserServiceClient is the client API for IntentParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntentParserServiceClient interface {
	DoSomething(ctx context.Context, in *IntentParserRequest, opts ...grpc.CallOption) (*IntentParserResponse, error)
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type intentParserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntentParserServiceClient(cc grpc.ClientConnInterface) IntentParserServiceClient {
	return &intentParserServiceClient{cc}
}

func (c *intentParserServiceClient) DoSomething(ctx context.Context, in *IntentParserRequest, opts ...grpc.CallOption) (*IntentParserResponse, error) {
	out := new(IntentParserResponse)
	err := c.cc.Invoke(ctx, IntentParserService_DoSomething_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intentParserServiceClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IntentParserService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntentParserServiceServer is the server API for IntentParserService service.
// All implementations must embed UnimplementedIntentParserServiceServer
// for forward compatibility
type IntentParserServiceServer interface {
	DoSomething(context.Context, *IntentParserRequest) (*IntentParserResponse, error)
	HealthCheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedIntentParserServiceServer()
}

// UnimplementedIntentParserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIntentParserServiceServer struct {
}

func (UnimplementedIntentParserServiceServer) DoSomething(context.Context, *IntentParserRequest) (*IntentParserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSomething not implemented")
}
func (UnimplementedIntentParserServiceServer) HealthCheck(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedIntentParserServiceServer) mustEmbedUnimplementedIntentParserServiceServer() {}

// UnsafeIntentParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntentParserServiceServer will
// result in compilation errors.
type UnsafeIntentParserServiceServer interface {
	mustEmbedUnimplementedIntentParserServiceServer()
}

func RegisterIntentParserServiceServer(s grpc.ServiceRegistrar, srv IntentParserServiceServer) {
	s.RegisterService(&IntentParserService_ServiceDesc, srv)
}

func _IntentParserService_DoSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntentParserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentParserServiceServer).DoSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentParserService_DoSomething_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentParserServiceServer).DoSomething(ctx, req.(*IntentParserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IntentParserService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentParserServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IntentParserService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentParserServiceServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// IntentParserService_ServiceDesc is the grpc.ServiceDesc for IntentParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntentParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenant_parser.IntentParserService",
	HandlerType: (*IntentParserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoSomething",
			Handler:    _IntentParserService_DoSomething_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _IntentParserService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenant_parser.proto",
}
