# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template/template.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17template/template.proto\x12\x08template\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0cPingResponse\x12\r\n\x05reply\x18\x01 \x01(\t2H\n\x0fTemplateService\x12\x35\n\x04Ping\x12\x15.template.PingRequest\x1a\x16.template.PingResponseBWZUgithub.com/milkyhoop/backend/services/template-service-golang/internal/delivery/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'template.template_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZUgithub.com/milkyhoop/backend/services/template-service-golang/internal/delivery/pb;pb'
  _globals['_PINGREQUEST']._serialized_start=37
  _globals['_PINGREQUEST']._serialized_end=67
  _globals['_PINGRESPONSE']._serialized_start=69
  _globals['_PINGRESPONSE']._serialized_end=98
  _globals['_TEMPLATESERVICE']._serialized_start=100
  _globals['_TEMPLATESERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
