       matviewname       |                                                                                                                                                                                     definition                                                                                                                                                                                      
-------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 laporan_posisi_keuangan |  SELECT transaksi_harian.tenant_id,                                                                                                                                                                                                                                                                                                                                                +
                         |     date_trunc('month'::text, to_timestamp(((transaksi_harian."timestamp" / 1000))::double precision)) AS periode,                                                                                                                                                                                                                                                                 +
                         |     sum(                                                                                                                                                                                                                                                                                                                                                                           +
                         |         CASE                                                                                                                                                                                                                                                                                                                                                                       +
                         |             WHEN (((transaksi_harian.jenis_transaksi)::text = 'penjualan'::text) AND ((transaksi_harian.status)::text = 'approved'::text) AND ((transaksi_harian.payload ->> 'payment_status'::text) <> 'lunas'::text)) THEN (((transaksi_harian.payload ->> 'total_nominal'::text))::bigint - COALESCE(((transaksi_harian.payload ->> 'amount_paid'::text))::bigint, (0)::bigint))+
                         |             ELSE (0)::bigint                                                                                                                                                                                                                                                                                                                                                       +
                         |         END) AS piutang,                                                                                                                                                                                                                                                                                                                                                           +
                         |     sum(                                                                                                                                                                                                                                                                                                                                                                           +
                         |         CASE                                                                                                                                                                                                                                                                                                                                                                       +
                         |             WHEN (((transaksi_harian.jenis_transaksi)::text = 'pembelian'::text) AND ((transaksi_harian.status)::text = 'approved'::text) AND ((transaksi_harian.payload ->> 'payment_status'::text) <> 'lunas'::text)) THEN (((transaksi_harian.payload ->> 'total_nominal'::text))::bigint - COALESCE(((transaksi_harian.payload ->> 'amount_paid'::text))::bigint, (0)::bigint))+
                         |             ELSE (0)::bigint                                                                                                                                                                                                                                                                                                                                                       +
                         |         END) AS utang,                                                                                                                                                                                                                                                                                                                                                             +
                         |     sum(                                                                                                                                                                                                                                                                                                                                                                           +
                         |         CASE                                                                                                                                                                                                                                                                                                                                                                       +
                         |             WHEN (((transaksi_harian.jenis_transaksi)::text = 'penjualan'::text) AND ((transaksi_harian.status)::text = 'approved'::text)) THEN COALESCE(((transaksi_harian.payload ->> 'amount_paid'::text))::bigint, ((transaksi_harian.payload ->> 'total_nominal'::text))::bigint)                                                                                             +
                         |             WHEN (((transaksi_harian.jenis_transaksi)::text = 'pembelian'::text) AND ((transaksi_harian.status)::text = 'approved'::text)) THEN (- COALESCE(((transaksi_harian.payload ->> 'amount_paid'::text))::bigint, ((transaksi_harian.payload ->> 'total_nominal'::text))::bigint))                                                                                         +
                         |             WHEN (((transaksi_harian.jenis_transaksi)::text = 'beban'::text) AND ((transaksi_harian.status)::text = 'approved'::text)) THEN (- ((transaksi_harian.payload ->> 'nominal'::text))::bigint)                                                                                                                                                                           +
                         |             ELSE (0)::bigint                                                                                                                                                                                                                                                                                                                                                       +
                         |         END) AS kas_bank,                                                                                                                                                                                                                                                                                                                                                          +
                         |     max(transaksi_harian.updated_at) AS last_updated                                                                                                                                                                                                                                                                                                                               +
                         |    FROM transaksi_harian                                                                                                                                                                                                                                                                                                                                                           +
                         |   WHERE ((transaksi_harian.status)::text = 'approved'::text)                                                                                                                                                                                                                                                                                                                       +
                         |   GROUP BY transaksi_harian.tenant_id, (date_trunc('month'::text, to_timestamp(((transaksi_harian."timestamp" / 1000))::double precision)));
(1 row)

