version: '3.8'

services:
  cust_context:
    build:
      context: .
      dockerfile: backend/services/cust_context/Dockerfile
    ports:
      - "7008:5008"
      - "8080:8080"
    networks:
      - internal
    environment:
      - GRPC_PORT=5008
      - HTTP_PORT=8080
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - ./logs/cust_context:/var/log
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:5008"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    depends_on:
      - postgres
      - redis

  context_service:
    build:
      context: .
      dockerfile: backend/services/context_service/Dockerfile
    ports:
      - "7007:5007"
    networks:
      - internal
    environment:
      - GRPC_PORT=5007
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - ./logs/context_service:/var/log
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:5007"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    depends_on:
      - postgres
      - redis

  memory_service:
    build:
      context: .
      dockerfile: backend/services/memory_service/Dockerfile
    ports:
      - "7000:5000"
    networks:
      - internal
    environment:
      - GRPC_PORT=5000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - ./logs/memory_service:/var/log
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:5000"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    depends_on:
      - postgres
      - redis

  conversation_service:
    build:
      context: .
      dockerfile: backend/services/conversation_service/Dockerfile
    ports:
      - "7002:5002"
    networks:
      - internal
    environment:
      - GRPC_PORT=5002
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    volumes:
      - ./logs/conversation_service:/var/log
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=localhost:5002"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    depends_on:
      - postgres
      - redis

  flow-executor:
    build:
      context: .
      dockerfile: backend/services/flow-executor/Dockerfile
    ports:
      - "7088:8088"
    networks:
      - internal
    environment:
      - HTTP_PORT=8088
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - ./logs/flow-executor:/var/log
      - ./flows:/flows
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: always
    depends_on:
      - postgres

networks:
  internal:
    driver: bridge
