# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16template_service.proto\x12\x08template\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x16TemplateServiceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\"9\n\x17TemplateServiceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\xa4\x01\n\x0fTemplateService\x12R\n\x0b\x44oSomething\x12 .template.TemplateServiceRequest\x1a!.template.TemplateServiceResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBUZSgithub.com/milkyhoop/template-service-golang/internal/delivery/pb/template;templateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'template_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZSgithub.com/milkyhoop/template-service-golang/internal/delivery/pb/template;template'
  _globals['_TEMPLATESERVICEREQUEST']._serialized_start=65
  _globals['_TEMPLATESERVICEREQUEST']._serialized_end=121
  _globals['_TEMPLATESERVICERESPONSE']._serialized_start=123
  _globals['_TEMPLATESERVICERESPONSE']._serialized_end=180
  _globals['_TEMPLATESERVICE']._serialized_start=183
  _globals['_TEMPLATESERVICE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
