# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import ragcrud_service_pb2 as ragcrud__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ragcrud_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagCrudServiceStub(object):
    """option go_package = "github.com/milkyhoop/template-service-golang/internal/delivery/pb/template;template";
    option python_package = "app.protos";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoSomething = channel.unary_unary(
                '/ragcrud_service.RagCrudService/DoSomething',
                request_serializer=ragcrud__service__pb2.Ragcrud_serviceRequest.SerializeToString,
                response_deserializer=ragcrud__service__pb2.Ragcrud_serviceResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ragcrud_service.RagCrudService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateRagDocument = channel.unary_unary(
                '/ragcrud_service.RagCrudService/CreateRagDocument',
                request_serializer=ragcrud__service__pb2.CreateRagDocumentRequest.SerializeToString,
                response_deserializer=ragcrud__service__pb2.RagDocumentResponse.FromString,
                _registered_method=True)
        self.ListRagDocuments = channel.unary_unary(
                '/ragcrud_service.RagCrudService/ListRagDocuments',
                request_serializer=ragcrud__service__pb2.ListRagDocumentsRequest.SerializeToString,
                response_deserializer=ragcrud__service__pb2.ListRagDocumentsResponse.FromString,
                _registered_method=True)
        self.GetRagDocument = channel.unary_unary(
                '/ragcrud_service.RagCrudService/GetRagDocument',
                request_serializer=ragcrud__service__pb2.GetRagDocumentRequest.SerializeToString,
                response_deserializer=ragcrud__service__pb2.RagDocumentResponse.FromString,
                _registered_method=True)
        self.UpdateRagDocument = channel.unary_unary(
                '/ragcrud_service.RagCrudService/UpdateRagDocument',
                request_serializer=ragcrud__service__pb2.UpdateRagDocumentRequest.SerializeToString,
                response_deserializer=ragcrud__service__pb2.RagDocumentResponse.FromString,
                _registered_method=True)
        self.UpdateRagDocumentBySearch = channel.unary_unary(
                '/ragcrud_service.RagCrudService/UpdateRagDocumentBySearch',
                request_serializer=ragcrud__service__pb2.UpdateRagDocumentBySearchRequest.SerializeToString,
                response_deserializer=ragcrud__service__pb2.RagDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteRagDocument = channel.unary_unary(
                '/ragcrud_service.RagCrudService/DeleteRagDocument',
                request_serializer=ragcrud__service__pb2.DeleteRagDocumentRequest.SerializeToString,
                response_deserializer=ragcrud__service__pb2.RagDocumentResponse.FromString,
                _registered_method=True)
        self.FuzzySearchDocuments = channel.unary_unary(
                '/ragcrud_service.RagCrudService/FuzzySearchDocuments',
                request_serializer=ragcrud__service__pb2.FuzzySearchRequest.SerializeToString,
                response_deserializer=ragcrud__service__pb2.FuzzySearchResponse.FromString,
                _registered_method=True)


class RagCrudServiceServicer(object):
    """option go_package = "github.com/milkyhoop/template-service-golang/internal/delivery/pb/template;template";
    option python_package = "app.protos";

    """

    def DoSomething(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRagDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRagDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRagDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRagDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRagDocumentBySearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRagDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuzzySearchDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagCrudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoSomething': grpc.unary_unary_rpc_method_handler(
                    servicer.DoSomething,
                    request_deserializer=ragcrud__service__pb2.Ragcrud_serviceRequest.FromString,
                    response_serializer=ragcrud__service__pb2.Ragcrud_serviceResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateRagDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRagDocument,
                    request_deserializer=ragcrud__service__pb2.CreateRagDocumentRequest.FromString,
                    response_serializer=ragcrud__service__pb2.RagDocumentResponse.SerializeToString,
            ),
            'ListRagDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRagDocuments,
                    request_deserializer=ragcrud__service__pb2.ListRagDocumentsRequest.FromString,
                    response_serializer=ragcrud__service__pb2.ListRagDocumentsResponse.SerializeToString,
            ),
            'GetRagDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagDocument,
                    request_deserializer=ragcrud__service__pb2.GetRagDocumentRequest.FromString,
                    response_serializer=ragcrud__service__pb2.RagDocumentResponse.SerializeToString,
            ),
            'UpdateRagDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRagDocument,
                    request_deserializer=ragcrud__service__pb2.UpdateRagDocumentRequest.FromString,
                    response_serializer=ragcrud__service__pb2.RagDocumentResponse.SerializeToString,
            ),
            'UpdateRagDocumentBySearch': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRagDocumentBySearch,
                    request_deserializer=ragcrud__service__pb2.UpdateRagDocumentBySearchRequest.FromString,
                    response_serializer=ragcrud__service__pb2.RagDocumentResponse.SerializeToString,
            ),
            'DeleteRagDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRagDocument,
                    request_deserializer=ragcrud__service__pb2.DeleteRagDocumentRequest.FromString,
                    response_serializer=ragcrud__service__pb2.RagDocumentResponse.SerializeToString,
            ),
            'FuzzySearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.FuzzySearchDocuments,
                    request_deserializer=ragcrud__service__pb2.FuzzySearchRequest.FromString,
                    response_serializer=ragcrud__service__pb2.FuzzySearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ragcrud_service.RagCrudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ragcrud_service.RagCrudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagCrudService(object):
    """option go_package = "github.com/milkyhoop/template-service-golang/internal/delivery/pb/template;template";
    option python_package = "app.protos";

    """

    @staticmethod
    def DoSomething(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/DoSomething',
            ragcrud__service__pb2.Ragcrud_serviceRequest.SerializeToString,
            ragcrud__service__pb2.Ragcrud_serviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRagDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/CreateRagDocument',
            ragcrud__service__pb2.CreateRagDocumentRequest.SerializeToString,
            ragcrud__service__pb2.RagDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRagDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/ListRagDocuments',
            ragcrud__service__pb2.ListRagDocumentsRequest.SerializeToString,
            ragcrud__service__pb2.ListRagDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRagDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/GetRagDocument',
            ragcrud__service__pb2.GetRagDocumentRequest.SerializeToString,
            ragcrud__service__pb2.RagDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRagDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/UpdateRagDocument',
            ragcrud__service__pb2.UpdateRagDocumentRequest.SerializeToString,
            ragcrud__service__pb2.RagDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRagDocumentBySearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/UpdateRagDocumentBySearch',
            ragcrud__service__pb2.UpdateRagDocumentBySearchRequest.SerializeToString,
            ragcrud__service__pb2.RagDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRagDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/DeleteRagDocument',
            ragcrud__service__pb2.DeleteRagDocumentRequest.SerializeToString,
            ragcrud__service__pb2.RagDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FuzzySearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragcrud_service.RagCrudService/FuzzySearchDocuments',
            ragcrud__service__pb2.FuzzySearchRequest.SerializeToString,
            ragcrud__service__pb2.FuzzySearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
