# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\rorder_service\x1a\x1bgoogle/protobuf/empty.proto\"O\n\x12\x43reateOrderRequest\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x01(\t\x12\x13\n\x0btotal_price\x18\x03 \x01(\x01\"\x94\x01\n\x13\x43reateOrderResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rcustomer_name\x18\x02 \x01(\t\x12\r\n\x05items\x18\x03 \x01(\t\x12\x13\n\x0btotal_price\x18\x04 \x01(\x01\x12\x0e\n\x06status\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"6\n\x14Order_serviceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\"7\n\x15Order_serviceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\xfe\x01\n\rOrder_service\x12T\n\x0b\x43reateOrder\x12!.order_service.CreateOrderRequest\x1a\".order_service.CreateOrderResponse\x12X\n\x0b\x44oSomething\x12#.order_service.Order_serviceRequest\x1a$.order_service.Order_serviceResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBEZCgithub.com/milkyhoop/order-service/internal/delivery/pb/order;orderb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/milkyhoop/order-service/internal/delivery/pb/order;order'
  _globals['_CREATEORDERREQUEST']._serialized_start=67
  _globals['_CREATEORDERREQUEST']._serialized_end=146
  _globals['_CREATEORDERRESPONSE']._serialized_start=149
  _globals['_CREATEORDERRESPONSE']._serialized_end=297
  _globals['_ORDER_SERVICEREQUEST']._serialized_start=299
  _globals['_ORDER_SERVICEREQUEST']._serialized_end=353
  _globals['_ORDER_SERVICERESPONSE']._serialized_start=355
  _globals['_ORDER_SERVICERESPONSE']._serialized_end=410
  _globals['_ORDER_SERVICE']._serialized_start=413
  _globals['_ORDER_SERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
