BEGIN;
DELETE FROM role_permissions WHERE module IN (
    'EXPENSE','DEBIT_NOTE','QUOTE','SALES_ORDER','CREDIT_NOTE','TABLES','CUSTOMER_DEPOSIT','VENDOR_DEPOSIT',
    'STOCK_ADJUST','WAREHOUSE','UNIT','BOM','WORK_ORDER','WORK_CENTER','MATERIAL_ISSUE','FG_RECEIPT',
    'FIXED_ASSET','INTERCOMPANY','LEDGER','PERIOD','BUDGET','AR_AGING','EMPLOYEE','BPJS','PAY_GROUP','SALARY_COMPONENT');
DELETE FROM schema_migrations WHERE version = 'V251__role_permissions_26_modul.sql';
COMMIT;
