-- V265 ROLLBACK
BEGIN;
DROP TRIGGER IF EXISTS trg_search_text_customers ON customers;
DROP FUNCTION IF EXISTS fn_search_text_customers();
DROP INDEX IF EXISTS idx_customers_search_trgm;
ALTER TABLE customers DROP COLUMN IF EXISTS search_text;
DROP TRIGGER IF EXISTS trg_search_text_vendors ON vendors;
DROP FUNCTION IF EXISTS fn_search_text_vendors();
DROP INDEX IF EXISTS idx_vendors_search_trgm;
ALTER TABLE vendors DROP COLUMN IF EXISTS search_text;
DROP TRIGGER IF EXISTS trg_search_text_sales_invoices ON sales_invoices;
DROP FUNCTION IF EXISTS fn_search_text_sales_invoices();
DROP INDEX IF EXISTS idx_sales_invoices_search_trgm;
ALTER TABLE sales_invoices DROP COLUMN IF EXISTS search_text;
DROP TRIGGER IF EXISTS trg_search_text_quotes ON quotes;
DROP FUNCTION IF EXISTS fn_search_text_quotes();
DROP INDEX IF EXISTS idx_quotes_search_trgm;
ALTER TABLE quotes DROP COLUMN IF EXISTS search_text;
DROP TRIGGER IF EXISTS trg_search_text_sales_orders ON sales_orders;
DROP FUNCTION IF EXISTS fn_search_text_sales_orders();
DROP INDEX IF EXISTS idx_sales_orders_search_trgm;
ALTER TABLE sales_orders DROP COLUMN IF EXISTS search_text;
DROP TRIGGER IF EXISTS trg_search_text_sales_order_shipments ON sales_order_shipments;
DROP FUNCTION IF EXISTS fn_search_text_sales_order_shipments();
DROP INDEX IF EXISTS idx_sales_order_shipments_search_trgm;
ALTER TABLE sales_order_shipments DROP COLUMN IF EXISTS search_text;
DROP TRIGGER IF EXISTS trg_search_text_receive_payments ON receive_payments;
DROP FUNCTION IF EXISTS fn_search_text_receive_payments();
DROP INDEX IF EXISTS idx_receive_payments_search_trgm;
ALTER TABLE receive_payments DROP COLUMN IF EXISTS search_text;
DROP TRIGGER IF EXISTS trg_search_text_customer_deposits ON customer_deposits;
DROP FUNCTION IF EXISTS fn_search_text_customer_deposits();
DROP INDEX IF EXISTS idx_customer_deposits_search_trgm;
ALTER TABLE customer_deposits DROP COLUMN IF EXISTS search_text;
DROP TRIGGER IF EXISTS trg_search_text_credit_notes ON credit_notes;
DROP FUNCTION IF EXISTS fn_search_text_credit_notes();
DROP INDEX IF EXISTS idx_credit_notes_search_trgm;
ALTER TABLE credit_notes DROP COLUMN IF EXISTS search_text;
COMMIT;
