# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: outbox_worker.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13outbox_worker.proto\x12\routbox_worker\"\x14\n\x12HealthCheckRequest\"}\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12-\n\x07metrics\x18\x04 \x01(\x0b\x32\x1c.outbox_worker.WorkerMetrics\"?\n\x14ProcessOutboxRequest\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\x12\x13\n\x0b\x66orce_retry\x18\x02 \x01(\x08\"\x97\x01\n\x15ProcessOutboxResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fprocessed_count\x18\x02 \x01(\x05\x12\x14\n\x0c\x66\x61iled_count\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\x12-\n\x06\x65vents\x18\x05 \x03(\x0b\x32\x1d.outbox_worker.ProcessedEvent\"u\n\x0eProcessedEvent\x12\x11\n\toutbox_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x14\n\x0cprocessed_at\x18\x05 \x01(\x03\"\x15\n\x13WorkerStatusRequest\"\x9e\x01\n\x14WorkerStatusResponse\x12\x12\n\nis_running\x18\x01 \x01(\x08\x12\x12\n\nstarted_at\x18\x02 \x01(\x03\x12\x14\n\x0clast_poll_at\x18\x03 \x01(\x03\x12\x19\n\x11poll_interval_sec\x18\x04 \x01(\x05\x12-\n\x07metrics\x18\x05 \x01(\x0b\x32\x1c.outbox_worker.WorkerMetrics\"\x8a\x01\n\rWorkerMetrics\x12\x17\n\x0ftotal_processed\x18\x01 \x01(\x03\x12\x14\n\x0ctotal_failed\x18\x02 \x01(\x03\x12\x15\n\rpending_count\x18\x03 \x01(\x05\x12\x13\n\x0bretry_count\x18\x04 \x01(\x05\x12\x1e\n\x16\x61vg_processing_time_ms\x18\x05 \x01(\x01\x32\x9c\x02\n\x0cOutboxWorker\x12T\n\x0bHealthCheck\x12!.outbox_worker.HealthCheckRequest\x1a\".outbox_worker.HealthCheckResponse\x12Z\n\rProcessOutbox\x12#.outbox_worker.ProcessOutboxRequest\x1a$.outbox_worker.ProcessOutboxResponse\x12Z\n\x0fGetWorkerStatus\x12\".outbox_worker.WorkerStatusRequest\x1a#.outbox_worker.WorkerStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'outbox_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=38
  _globals['_HEALTHCHECKREQUEST']._serialized_end=58
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=60
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=185
  _globals['_PROCESSOUTBOXREQUEST']._serialized_start=187
  _globals['_PROCESSOUTBOXREQUEST']._serialized_end=250
  _globals['_PROCESSOUTBOXRESPONSE']._serialized_start=253
  _globals['_PROCESSOUTBOXRESPONSE']._serialized_end=404
  _globals['_PROCESSEDEVENT']._serialized_start=406
  _globals['_PROCESSEDEVENT']._serialized_end=523
  _globals['_WORKERSTATUSREQUEST']._serialized_start=525
  _globals['_WORKERSTATUSREQUEST']._serialized_end=546
  _globals['_WORKERSTATUSRESPONSE']._serialized_start=549
  _globals['_WORKERSTATUSRESPONSE']._serialized_end=707
  _globals['_WORKERMETRICS']._serialized_start=710
  _globals['_WORKERMETRICS']._serialized_end=848
  _globals['_OUTBOXWORKER']._serialized_start=851
  _globals['_OUTBOXWORKER']._serialized_end=1135
# @@protoc_insertion_point(module_scope)
