# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import hoop_registry_pb2 as hoop__registry__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hoop_registry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HoopRegistryStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterHoop = channel.unary_unary(
                '/hoop_registry.HoopRegistry/RegisterHoop',
                request_serializer=hoop__registry__pb2.RegisterHoopRequest.SerializeToString,
                response_deserializer=hoop__registry__pb2.RegisterHoopResponse.FromString,
                _registered_method=True)
        self.GetHoopMetadata = channel.unary_unary(
                '/hoop_registry.HoopRegistry/GetHoopMetadata',
                request_serializer=hoop__registry__pb2.GetHoopMetadataRequest.SerializeToString,
                response_deserializer=hoop__registry__pb2.GetHoopMetadataResponse.FromString,
                _registered_method=True)
        self.ListHoop = channel.unary_unary(
                '/hoop_registry.HoopRegistry/ListHoop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=hoop__registry__pb2.ListHoopResponse.FromString,
                _registered_method=True)
        self.UpdateHoopMetadata = channel.unary_unary(
                '/hoop_registry.HoopRegistry/UpdateHoopMetadata',
                request_serializer=hoop__registry__pb2.UpdateHoopMetadataRequest.SerializeToString,
                response_deserializer=hoop__registry__pb2.UpdateHoopMetadataResponse.FromString,
                _registered_method=True)
        self.DeleteHoop = channel.unary_unary(
                '/hoop_registry.HoopRegistry/DeleteHoop',
                request_serializer=hoop__registry__pb2.DeleteHoopRequest.SerializeToString,
                response_deserializer=hoop__registry__pb2.DeleteHoopResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hoop_registry.HoopRegistry/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SearchHoop = channel.unary_unary(
                '/hoop_registry.HoopRegistry/SearchHoop',
                request_serializer=hoop__registry__pb2.SearchHoopRequest.SerializeToString,
                response_deserializer=hoop__registry__pb2.ListHoopResponse.FromString,
                _registered_method=True)


class HoopRegistryServicer(object):
    """Service definition
    """

    def RegisterHoop(self, request, context):
        """Register a new hoop to the registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHoopMetadata(self, request, context):
        """Get metadata for a specific hoop by name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHoop(self, request, context):
        """List all registered hoops
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateHoopMetadata(self, request, context):
        """Update metadata for a specific hoop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteHoop(self, request, context):
        """Delete a hoop from the registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchHoop(self, request, context):
        """Search hoops by keyword
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HoopRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterHoop': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHoop,
                    request_deserializer=hoop__registry__pb2.RegisterHoopRequest.FromString,
                    response_serializer=hoop__registry__pb2.RegisterHoopResponse.SerializeToString,
            ),
            'GetHoopMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHoopMetadata,
                    request_deserializer=hoop__registry__pb2.GetHoopMetadataRequest.FromString,
                    response_serializer=hoop__registry__pb2.GetHoopMetadataResponse.SerializeToString,
            ),
            'ListHoop': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHoop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=hoop__registry__pb2.ListHoopResponse.SerializeToString,
            ),
            'UpdateHoopMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateHoopMetadata,
                    request_deserializer=hoop__registry__pb2.UpdateHoopMetadataRequest.FromString,
                    response_serializer=hoop__registry__pb2.UpdateHoopMetadataResponse.SerializeToString,
            ),
            'DeleteHoop': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteHoop,
                    request_deserializer=hoop__registry__pb2.DeleteHoopRequest.FromString,
                    response_serializer=hoop__registry__pb2.DeleteHoopResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SearchHoop': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchHoop,
                    request_deserializer=hoop__registry__pb2.SearchHoopRequest.FromString,
                    response_serializer=hoop__registry__pb2.ListHoopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hoop_registry.HoopRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hoop_registry.HoopRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HoopRegistry(object):
    """Service definition
    """

    @staticmethod
    def RegisterHoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoop_registry.HoopRegistry/RegisterHoop',
            hoop__registry__pb2.RegisterHoopRequest.SerializeToString,
            hoop__registry__pb2.RegisterHoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHoopMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoop_registry.HoopRegistry/GetHoopMetadata',
            hoop__registry__pb2.GetHoopMetadataRequest.SerializeToString,
            hoop__registry__pb2.GetHoopMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoop_registry.HoopRegistry/ListHoop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            hoop__registry__pb2.ListHoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateHoopMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoop_registry.HoopRegistry/UpdateHoopMetadata',
            hoop__registry__pb2.UpdateHoopMetadataRequest.SerializeToString,
            hoop__registry__pb2.UpdateHoopMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteHoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoop_registry.HoopRegistry/DeleteHoop',
            hoop__registry__pb2.DeleteHoopRequest.SerializeToString,
            hoop__registry__pb2.DeleteHoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoop_registry.HoopRegistry/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchHoop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hoop_registry.HoopRegistry/SearchHoop',
            hoop__registry__pb2.SearchHoopRequest.SerializeToString,
            hoop__registry__pb2.ListHoopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
