# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template client.py.jinja --
import warnings
import logging
from datetime import timedelta
from pathlib import Path
from types import TracebackType
from typing_extensions import override

from pydantic import BaseModel

from . import types, models, errors, actions
from ._base_client import BasePrisma, UseClientDefault, USE_CLIENT_DEFAULT
from .types import DatasourceOverride, HttpConfig, MetricsFormat
from ._types import BaseModelT, PrismaMethod, TransactionId, Datasource
from .bases import _PrismaModel
from ._builder import QueryBuilder, dumps
from .generator.models import EngineType, OptionalValueFromEnvVar, BinaryPaths
from ._compat import removeprefix, model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED, DEFAULT_CONNECT_TIMEOUT, DEFAULT_TX_MAX_WAIT, DEFAULT_TX_TIMEOUT
from ._raw_query import deserialize_raw_results
from ._metrics import Metrics
from .metadata import PRISMA_MODELS, RELATIONAL_FIELD_MAPPINGS
from ._transactions import AsyncTransactionManager, SyncTransactionManager

# re-exports
from ._base_client import SyncBasePrisma, AsyncBasePrisma, load_env as load_env
from ._registry import (
    register as register,
    get_client as get_client,
    RegisteredClient as RegisteredClient,
)


__all__ = (
    'ENGINE_TYPE',
    'SCHEMA_PATH',
    'BINARY_PATHS',
    'Batch',
    'Prisma',
    'Client',
    'load_env',
    'register',
    'get_client',
)

log: logging.Logger = logging.getLogger(__name__)

SCHEMA_PATH = Path('/root/milkyhoop/database/schemas/global_schema.prisma')
PACKAGED_SCHEMA_PATH = Path(__file__).parent.joinpath('schema.prisma')
ENGINE_TYPE: EngineType = EngineType.binary
BINARY_PATHS = model_parse(BinaryPaths, {'queryEngine': {'debian-openssl-3.0.x': '/root/milkyhoop/node_modules/prisma/query-engine-debian-openssl-3.0.x'}, 'introspectionEngine': {}, 'migrationEngine': {}, 'libqueryEngine': {}, 'prismaFmt': {}})


class Prisma(AsyncBasePrisma):
    # Note: these property names can be customised using `/// @Python(instance_name: '...')`
    # https://prisma-client-py.readthedocs.io/en/stable/reference/schema-extensions/#instance_name
    user: 'actions.UserActions[models.User]'
    account: 'actions.AccountActions[models.Account]'
    session: 'actions.SessionActions[models.Session]'
    usersecurity: 'actions.UserSecurityActions[models.UserSecurity]'
    userprofile: 'actions.UserProfileActions[models.UserProfile]'
    verificationtoken: 'actions.VerificationTokenActions[models.VerificationToken]'
    messages: 'actions.messagesActions[models.messages]'
    userbusiness: 'actions.UserBusinessActions[models.UserBusiness]'
    userlocations: 'actions.UserLocationsActions[models.UserLocations]'
    userfinance: 'actions.UserFinanceActions[models.UserFinance]'
    usersubscriptions: 'actions.UserSubscriptionsActions[models.UserSubscriptions]'
    plans: 'actions.PlansActions[models.Plans]'
    useraisettings: 'actions.UserAISettingsActions[models.UserAISettings]'
    usermedia: 'actions.UserMediaActions[models.UserMedia]'
    tenant: 'actions.TenantActions[models.Tenant]'
    order: 'actions.OrderActions[models.Order]'
    memory: 'actions.MemoryActions[models.Memory]'
    ragdocument: 'actions.RagDocumentActions[models.RagDocument]'

    __slots__ = (
        'user',
        'account',
        'session',
        'usersecurity',
        'userprofile',
        'verificationtoken',
        'messages',
        'userbusiness',
        'userlocations',
        'userfinance',
        'usersubscriptions',
        'plans',
        'useraisettings',
        'usermedia',
        'tenant',
        'order',
        'memory',
        'ragdocument',
    )

    def __init__(
        self,
        *,
        use_dotenv: bool = True,
        log_queries: bool = False,
        auto_register: bool = False,
        datasource: DatasourceOverride | None = None,
        connect_timeout: int | timedelta = DEFAULT_CONNECT_TIMEOUT,
        http: HttpConfig | None = None,
    ) -> None:
        super().__init__(
            http=http,
            use_dotenv=use_dotenv,
            log_queries=log_queries,
            datasource=datasource,
            connect_timeout=connect_timeout,
        )
        self._set_generated_properties(
            schema_path=SCHEMA_PATH,
            engine_type=ENGINE_TYPE,
            prisma_models=PRISMA_MODELS,
            packaged_schema_path=PACKAGED_SCHEMA_PATH,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
            preview_features=set([]),
            active_provider='postgresql',
            default_datasource_name='db',
        )

        self.user = actions.UserActions[models.User](self, models.User)
        self.account = actions.AccountActions[models.Account](self, models.Account)
        self.session = actions.SessionActions[models.Session](self, models.Session)
        self.usersecurity = actions.UserSecurityActions[models.UserSecurity](self, models.UserSecurity)
        self.userprofile = actions.UserProfileActions[models.UserProfile](self, models.UserProfile)
        self.verificationtoken = actions.VerificationTokenActions[models.VerificationToken](self, models.VerificationToken)
        self.messages = actions.messagesActions[models.messages](self, models.messages)
        self.userbusiness = actions.UserBusinessActions[models.UserBusiness](self, models.UserBusiness)
        self.userlocations = actions.UserLocationsActions[models.UserLocations](self, models.UserLocations)
        self.userfinance = actions.UserFinanceActions[models.UserFinance](self, models.UserFinance)
        self.usersubscriptions = actions.UserSubscriptionsActions[models.UserSubscriptions](self, models.UserSubscriptions)
        self.plans = actions.PlansActions[models.Plans](self, models.Plans)
        self.useraisettings = actions.UserAISettingsActions[models.UserAISettings](self, models.UserAISettings)
        self.usermedia = actions.UserMediaActions[models.UserMedia](self, models.UserMedia)
        self.tenant = actions.TenantActions[models.Tenant](self, models.Tenant)
        self.order = actions.OrderActions[models.Order](self, models.Order)
        self.memory = actions.MemoryActions[models.Memory](self, models.Memory)
        self.ragdocument = actions.RagDocumentActions[models.RagDocument](self, models.RagDocument)

        if auto_register:
            register(self)

    @property
    @override
    def _default_datasource(self) -> Datasource:
        return {
            'name': 'db',
            'url': OptionalValueFromEnvVar(**{'value': None, 'fromEnvVar': 'DATABASE_URL'}).resolve(),
            'source_file_path': '/root/milkyhoop/database/schemas/global_schema.prisma',
        }

    async def execute_raw(self, query: LiteralString, *args: Any) -> int:
        resp = await self._execute(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=None,
        )
        return int(resp['data']['result'])

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> dict[str, Any]:
        ...

    @overload
    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> Optional[BaseModelT]:
        ...

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[Optional[BaseModelT], dict[str, Any]]:
        """This function is the exact same as `query_raw()` but returns the first result.

        If model is given, the returned record is converted to the pydantic model first,
        otherwise a raw dictionary will be returned.
        """
        results: Sequence[Union[BaseModelT, dict[str, Any]]]
        if model is not None:
            results = await self.query_raw(query, *args, model=model)
        else:
            results = await self.query_raw(query, *args)

        if not results:
            return None

        return results[0]

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[dict[str, Any]]:
        ...

    @overload
    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Type[BaseModelT],
    ) -> List[BaseModelT]:
        ...

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
        model: Optional[Type[BaseModelT]] = None,
    ) -> Union[List[BaseModelT], List[dict[str, Any]]]:
        """Execute a raw SQL query against the database.

        If model is given, each returned record is converted to the pydantic model first,
        otherwise results will be raw dictionaries.
        """
        resp = await self._execute(
            method='query_raw',
            arguments={
                'query': query,
                'parameters': args,
            },
            model=model,
        )
        result = resp['data']['result']
        if model is not None:
            return deserialize_raw_results(result, model=model)

        return deserialize_raw_results(result)

    def batch_(self) -> Batch:
        """Returns a context manager for grouping write queries into a single transaction."""
        return Batch(client=self)

    def tx(
        self,
        *,
        max_wait: Union[int, timedelta] = DEFAULT_TX_MAX_WAIT,
        timeout: Union[int, timedelta] = DEFAULT_TX_TIMEOUT,
    ) -> TransactionManager:
        """Returns a context manager for executing queries within a database transaction.

        Entering the context manager returns a new Prisma instance wrapping all
        actions within a transaction, queries will be isolated to the Prisma instance and
        will not be commited to the database until the context manager exits.

        By default, Prisma will wait a maximum of 2 seconds to acquire a transaction from the database. You can modify this
        default with the `max_wait` argument which accepts a value in milliseconds or `datetime.timedelta`.

        By default, Prisma will cancel and rollback ay transactions that last longer than 5 seconds. You can modify this timeout
        with the `timeout` argument which accepts a value in milliseconds or `datetime.timedelta`.

        Example usage:

        ```py
        async with client.tx() as transaction:
            user1 = await client.user.create({'name': 'Robert'})
            user2 = await client.user.create({'name': 'Tegan'})
        ```

        In the above example, if the first database call succeeds but the second does not then neither of the records will be created.
        """
        return TransactionManager(
            client=self,
            max_wait=max_wait,
            timeout=timeout,
        )


TransactionManager = AsyncTransactionManager[Prisma]


# TODO: this should return the results as well
# TODO: don't require copy-pasting arguments between actions and batch actions
class Batch:
    user: 'UserBatchActions'
    account: 'AccountBatchActions'
    session: 'SessionBatchActions'
    usersecurity: 'UserSecurityBatchActions'
    userprofile: 'UserProfileBatchActions'
    verificationtoken: 'VerificationTokenBatchActions'
    messages: 'messagesBatchActions'
    userbusiness: 'UserBusinessBatchActions'
    userlocations: 'UserLocationsBatchActions'
    userfinance: 'UserFinanceBatchActions'
    usersubscriptions: 'UserSubscriptionsBatchActions'
    plans: 'PlansBatchActions'
    useraisettings: 'UserAISettingsBatchActions'
    usermedia: 'UserMediaBatchActions'
    tenant: 'TenantBatchActions'
    order: 'OrderBatchActions'
    memory: 'MemoryBatchActions'
    ragdocument: 'RagDocumentBatchActions'

    def __init__(self, client: Prisma) -> None:
        self.__client = client
        self.__queries: List[str] = []
        self._active_provider = client._active_provider
        self.user = UserBatchActions(self)
        self.account = AccountBatchActions(self)
        self.session = SessionBatchActions(self)
        self.usersecurity = UserSecurityBatchActions(self)
        self.userprofile = UserProfileBatchActions(self)
        self.verificationtoken = VerificationTokenBatchActions(self)
        self.messages = messagesBatchActions(self)
        self.userbusiness = UserBusinessBatchActions(self)
        self.userlocations = UserLocationsBatchActions(self)
        self.userfinance = UserFinanceBatchActions(self)
        self.usersubscriptions = UserSubscriptionsBatchActions(self)
        self.plans = PlansBatchActions(self)
        self.useraisettings = UserAISettingsBatchActions(self)
        self.usermedia = UserMediaBatchActions(self)
        self.tenant = TenantBatchActions(self)
        self.order = OrderBatchActions(self)
        self.memory = MemoryBatchActions(self)
        self.ragdocument = RagDocumentBatchActions(self)

    def _add(self, **kwargs: Any) -> None:
        builder = QueryBuilder(
            **kwargs,
            prisma_models=PRISMA_MODELS,
            relational_field_mappings=RELATIONAL_FIELD_MAPPINGS,
        )
        self.__queries.append(builder.build_query())

    async def commit(self) -> None:
        """Execute the queries"""
        # TODO: normalise this, we should still call client._execute
        queries = self.__queries
        self.__queries = []

        payload = {
            'batch': [
                {
                    'query': query,
                    'variables': {},
                }
                for query in queries
            ],
            'transaction': True,
        }
        await self.__client._engine.query(
            dumps(payload),
            tx_id=self.__client._tx_id,
        )

    def execute_raw(self, query: LiteralString, *args: Any) -> None:
        self._add(
            method='execute_raw',
            arguments={
                'query': query,
                'parameters': args,
            }
        )

    async def __aenter__(self) -> 'Batch':
        return self

    async def __aexit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        if exc is None:
            await self.commit()


# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserCreateInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.User,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.User,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserUpdateInput,
        where: types.UserWhereUniqueInput,
        include: Optional[types.UserInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.User,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserWhereUniqueInput,
        data: types.UserUpsertInput,
        include: Optional[types.UserInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.User,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserUpdateManyMutationInput,
        where: types.UserWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.User,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.User,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class AccountBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.AccountCreateInput,
        include: Optional[types.AccountInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Account,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.AccountCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Account,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.AccountWhereUniqueInput,
        include: Optional[types.AccountInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Account,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.AccountUpdateInput,
        where: types.AccountWhereUniqueInput,
        include: Optional[types.AccountInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Account,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.AccountWhereUniqueInput,
        data: types.AccountUpsertInput,
        include: Optional[types.AccountInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Account,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.AccountUpdateManyMutationInput,
        where: types.AccountWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Account,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.AccountWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Account,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class SessionBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.SessionCreateInput,
        include: Optional[types.SessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Session,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.SessionCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Session,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.SessionWhereUniqueInput,
        include: Optional[types.SessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Session,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.SessionUpdateInput,
        where: types.SessionWhereUniqueInput,
        include: Optional[types.SessionInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Session,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.SessionWhereUniqueInput,
        data: types.SessionUpsertInput,
        include: Optional[types.SessionInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Session,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.SessionUpdateManyMutationInput,
        where: types.SessionWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Session,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.SessionWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Session,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserSecurityBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserSecurityCreateInput,
        include: Optional[types.UserSecurityInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserSecurity,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserSecurityCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserSecurity,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserSecurityWhereUniqueInput,
        include: Optional[types.UserSecurityInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserSecurity,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserSecurityUpdateInput,
        where: types.UserSecurityWhereUniqueInput,
        include: Optional[types.UserSecurityInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserSecurity,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserSecurityWhereUniqueInput,
        data: types.UserSecurityUpsertInput,
        include: Optional[types.UserSecurityInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserSecurity,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserSecurityUpdateManyMutationInput,
        where: types.UserSecurityWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserSecurity,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserSecurityWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserSecurity,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserProfileBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserProfileCreateInput,
        include: Optional[types.UserProfileInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserProfile,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserProfileCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserProfile,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserProfileWhereUniqueInput,
        include: Optional[types.UserProfileInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserProfile,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserProfileUpdateInput,
        where: types.UserProfileWhereUniqueInput,
        include: Optional[types.UserProfileInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserProfile,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserProfileWhereUniqueInput,
        data: types.UserProfileUpsertInput,
        include: Optional[types.UserProfileInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserProfile,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserProfileUpdateManyMutationInput,
        where: types.UserProfileWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserProfile,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserProfileWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserProfile,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class VerificationTokenBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.VerificationTokenCreateInput,
        include: Optional[types.VerificationTokenInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.VerificationToken,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.VerificationTokenCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.VerificationToken,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.VerificationTokenWhereUniqueInput,
        include: Optional[types.VerificationTokenInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.VerificationToken,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.VerificationTokenUpdateInput,
        where: types.VerificationTokenWhereUniqueInput,
        include: Optional[types.VerificationTokenInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.VerificationToken,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.VerificationTokenWhereUniqueInput,
        data: types.VerificationTokenUpsertInput,
        include: Optional[types.VerificationTokenInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.VerificationToken,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.VerificationTokenUpdateManyMutationInput,
        where: types.VerificationTokenWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.VerificationToken,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.VerificationTokenWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.VerificationToken,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class messagesBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.messagesCreateInput,
        include: Optional[types.messagesInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.messages,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.messagesCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.messages,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.messagesWhereUniqueInput,
        include: Optional[types.messagesInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.messages,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.messagesUpdateInput,
        where: types.messagesWhereUniqueInput,
        include: Optional[types.messagesInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.messages,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.messagesWhereUniqueInput,
        data: types.messagesUpsertInput,
        include: Optional[types.messagesInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.messages,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.messagesUpdateManyMutationInput,
        where: types.messagesWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.messages,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.messagesWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.messages,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserBusinessBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserBusinessCreateInput,
        include: Optional[types.UserBusinessInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserBusiness,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserBusinessCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserBusiness,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserBusinessWhereUniqueInput,
        include: Optional[types.UserBusinessInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserBusiness,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserBusinessUpdateInput,
        where: types.UserBusinessWhereUniqueInput,
        include: Optional[types.UserBusinessInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserBusiness,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserBusinessWhereUniqueInput,
        data: types.UserBusinessUpsertInput,
        include: Optional[types.UserBusinessInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserBusiness,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserBusinessUpdateManyMutationInput,
        where: types.UserBusinessWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserBusiness,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserBusinessWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserBusiness,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserLocationsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserLocationsCreateInput,
        include: Optional[types.UserLocationsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserLocations,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserLocationsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserLocations,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserLocationsWhereUniqueInput,
        include: Optional[types.UserLocationsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserLocations,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserLocationsUpdateInput,
        where: types.UserLocationsWhereUniqueInput,
        include: Optional[types.UserLocationsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserLocations,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserLocationsWhereUniqueInput,
        data: types.UserLocationsUpsertInput,
        include: Optional[types.UserLocationsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserLocations,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserLocationsUpdateManyMutationInput,
        where: types.UserLocationsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserLocations,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserLocationsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserLocations,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserFinanceBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserFinanceCreateInput,
        include: Optional[types.UserFinanceInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserFinance,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserFinanceCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserFinance,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserFinanceWhereUniqueInput,
        include: Optional[types.UserFinanceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserFinance,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserFinanceUpdateInput,
        where: types.UserFinanceWhereUniqueInput,
        include: Optional[types.UserFinanceInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserFinance,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserFinanceWhereUniqueInput,
        data: types.UserFinanceUpsertInput,
        include: Optional[types.UserFinanceInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserFinance,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserFinanceUpdateManyMutationInput,
        where: types.UserFinanceWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserFinance,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserFinanceWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserFinance,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserSubscriptionsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserSubscriptionsCreateInput,
        include: Optional[types.UserSubscriptionsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserSubscriptions,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserSubscriptionsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserSubscriptions,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserSubscriptionsWhereUniqueInput,
        include: Optional[types.UserSubscriptionsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserSubscriptions,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserSubscriptionsUpdateInput,
        where: types.UserSubscriptionsWhereUniqueInput,
        include: Optional[types.UserSubscriptionsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserSubscriptions,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserSubscriptionsWhereUniqueInput,
        data: types.UserSubscriptionsUpsertInput,
        include: Optional[types.UserSubscriptionsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserSubscriptions,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserSubscriptionsUpdateManyMutationInput,
        where: types.UserSubscriptionsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserSubscriptions,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserSubscriptionsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserSubscriptions,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class PlansBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.PlansCreateInput,
        include: Optional[types.PlansInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Plans,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.PlansCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Plans,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.PlansWhereUniqueInput,
        include: Optional[types.PlansInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Plans,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.PlansUpdateInput,
        where: types.PlansWhereUniqueInput,
        include: Optional[types.PlansInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Plans,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.PlansWhereUniqueInput,
        data: types.PlansUpsertInput,
        include: Optional[types.PlansInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Plans,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.PlansUpdateManyMutationInput,
        where: types.PlansWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Plans,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.PlansWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Plans,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserAISettingsBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserAISettingsCreateInput,
        include: Optional[types.UserAISettingsInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserAISettings,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserAISettingsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserAISettings,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserAISettingsWhereUniqueInput,
        include: Optional[types.UserAISettingsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserAISettings,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserAISettingsUpdateInput,
        where: types.UserAISettingsWhereUniqueInput,
        include: Optional[types.UserAISettingsInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserAISettings,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserAISettingsWhereUniqueInput,
        data: types.UserAISettingsUpsertInput,
        include: Optional[types.UserAISettingsInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserAISettings,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserAISettingsUpdateManyMutationInput,
        where: types.UserAISettingsWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserAISettings,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserAISettingsWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserAISettings,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class UserMediaBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.UserMediaCreateInput,
        include: Optional[types.UserMediaInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.UserMedia,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.UserMediaCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.UserMedia,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.UserMediaWhereUniqueInput,
        include: Optional[types.UserMediaInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.UserMedia,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.UserMediaUpdateInput,
        where: types.UserMediaWhereUniqueInput,
        include: Optional[types.UserMediaInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.UserMedia,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.UserMediaWhereUniqueInput,
        data: types.UserMediaUpsertInput,
        include: Optional[types.UserMediaInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.UserMedia,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.UserMediaUpdateManyMutationInput,
        where: types.UserMediaWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.UserMedia,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.UserMediaWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.UserMedia,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class TenantBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.TenantCreateInput,
        include: Optional[types.TenantInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Tenant,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.TenantCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Tenant,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.TenantWhereUniqueInput,
        include: Optional[types.TenantInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Tenant,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.TenantUpdateInput,
        where: types.TenantWhereUniqueInput,
        include: Optional[types.TenantInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Tenant,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.TenantWhereUniqueInput,
        data: types.TenantUpsertInput,
        include: Optional[types.TenantInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Tenant,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.TenantUpdateManyMutationInput,
        where: types.TenantWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Tenant,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.TenantWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Tenant,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class OrderBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.OrderCreateInput,
        include: Optional[types.OrderInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Order,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.OrderCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Order,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.OrderWhereUniqueInput,
        include: Optional[types.OrderInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Order,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.OrderUpdateInput,
        where: types.OrderWhereUniqueInput,
        include: Optional[types.OrderInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Order,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.OrderWhereUniqueInput,
        data: types.OrderUpsertInput,
        include: Optional[types.OrderInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Order,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.OrderUpdateManyMutationInput,
        where: types.OrderWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Order,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.OrderWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Order,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class MemoryBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.MemoryCreateInput,
        include: Optional[types.MemoryInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.Memory,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.MemoryCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.Memory,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.MemoryWhereUniqueInput,
        include: Optional[types.MemoryInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.Memory,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.MemoryUpdateInput,
        where: types.MemoryWhereUniqueInput,
        include: Optional[types.MemoryInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.Memory,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.MemoryWhereUniqueInput,
        data: types.MemoryUpsertInput,
        include: Optional[types.MemoryInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.Memory,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.MemoryUpdateManyMutationInput,
        where: types.MemoryWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.Memory,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.MemoryWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.Memory,
            arguments={'where': where},
            root_selection=['count'],
        )



# NOTE: some arguments are meaningless in this context but are included
# for completeness sake
class RagDocumentBatchActions:
    def __init__(self, batcher: Batch) -> None:
        self._batcher = batcher

    def create(
        self,
        data: types.RagDocumentCreateInput,
        include: Optional[types.RagDocumentInclude] = None
    ) -> None:
        self._batcher._add(
            method='create',
            model=models.RagDocument,
            arguments={
                'data': data,
                'include': include,
            },
        )

    def create_many(
        self,
        data: List[types.RagDocumentCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> None:
        if skip_duplicates and self._batcher._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._batcher._active_provider, 'create_many_skip_duplicates')

        self._batcher._add(
            method='create_many',
            model=models.RagDocument,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )

    def delete(
        self,
        where: types.RagDocumentWhereUniqueInput,
        include: Optional[types.RagDocumentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='delete',
            model=models.RagDocument,
            arguments={
                'where': where,
                'include': include,
            },
        )

    def update(
        self,
        data: types.RagDocumentUpdateInput,
        where: types.RagDocumentWhereUniqueInput,
        include: Optional[types.RagDocumentInclude] = None
    ) -> None:
        self._batcher._add(
            method='update',
            model=models.RagDocument,
            arguments={
                'data': data,
                'where': where,
                'include': include,
            },
        )

    def upsert(
        self,
        where: types.RagDocumentWhereUniqueInput,
        data: types.RagDocumentUpsertInput,
        include: Optional[types.RagDocumentInclude] = None,
    ) -> None:
        self._batcher._add(
            method='upsert',
            model=models.RagDocument,
            arguments={
                'where': where,
                'include': include,
                'create': await data.get('create'),
                'update': await data.get('update'),
            },
        )

    def update_many(
        self,
        data: types.RagDocumentUpdateManyMutationInput,
        where: types.RagDocumentWhereInput,
    ) -> None:
        self._batcher._add(
            method='update_many',
            model=models.RagDocument,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )

    def delete_many(
        self,
        where: Optional[types.RagDocumentWhereInput] = None,
    ) -> None:
        self._batcher._add(
            method='delete_many',
            model=models.RagDocument,
            arguments={'where': where},
            root_selection=['count'],
        )



Client = Prisma