// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: ragllm_service.proto

package ragllm_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RagLlmService_DoSomething_FullMethodName            = "/ragllm_service.RagLlmService/DoSomething"
	RagLlmService_HealthCheck_FullMethodName            = "/ragllm_service.RagLlmService/HealthCheck"
	RagLlmService_GenerateEmbedding_FullMethodName      = "/ragllm_service.RagLlmService/GenerateEmbedding"
	RagLlmService_SearchSimilarDocuments_FullMethodName = "/ragllm_service.RagLlmService/SearchSimilarDocuments"
	RagLlmService_GenerateAnswer_FullMethodName         = "/ragllm_service.RagLlmService/GenerateAnswer"
)

// RagLlmServiceClient is the client API for RagLlmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagLlmServiceClient interface {
	DoSomething(ctx context.Context, in *RagllmServiceRequest, opts ...grpc.CallOption) (*RagllmServiceResponse, error)
	HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	GenerateEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error)
	SearchSimilarDocuments(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GenerateAnswer(ctx context.Context, in *GenerateAnswerRequest, opts ...grpc.CallOption) (*GenerateAnswerResponse, error)
}

type ragLlmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagLlmServiceClient(cc grpc.ClientConnInterface) RagLlmServiceClient {
	return &ragLlmServiceClient{cc}
}

func (c *ragLlmServiceClient) DoSomething(ctx context.Context, in *RagllmServiceRequest, opts ...grpc.CallOption) (*RagllmServiceResponse, error) {
	out := new(RagllmServiceResponse)
	err := c.cc.Invoke(ctx, RagLlmService_DoSomething_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragLlmServiceClient) HealthCheck(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, RagLlmService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragLlmServiceClient) GenerateEmbedding(ctx context.Context, in *EmbeddingRequest, opts ...grpc.CallOption) (*EmbeddingResponse, error) {
	out := new(EmbeddingResponse)
	err := c.cc.Invoke(ctx, RagLlmService_GenerateEmbedding_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragLlmServiceClient) SearchSimilarDocuments(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RagLlmService_SearchSimilarDocuments_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragLlmServiceClient) GenerateAnswer(ctx context.Context, in *GenerateAnswerRequest, opts ...grpc.CallOption) (*GenerateAnswerResponse, error) {
	out := new(GenerateAnswerResponse)
	err := c.cc.Invoke(ctx, RagLlmService_GenerateAnswer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagLlmServiceServer is the server API for RagLlmService service.
// All implementations must embed UnimplementedRagLlmServiceServer
// for forward compatibility
type RagLlmServiceServer interface {
	DoSomething(context.Context, *RagllmServiceRequest) (*RagllmServiceResponse, error)
	HealthCheck(context.Context, *empty.Empty) (*empty.Empty, error)
	GenerateEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error)
	SearchSimilarDocuments(context.Context, *SearchRequest) (*SearchResponse, error)
	GenerateAnswer(context.Context, *GenerateAnswerRequest) (*GenerateAnswerResponse, error)
	mustEmbedUnimplementedRagLlmServiceServer()
}

// UnimplementedRagLlmServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRagLlmServiceServer struct {
}

func (UnimplementedRagLlmServiceServer) DoSomething(context.Context, *RagllmServiceRequest) (*RagllmServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoSomething not implemented")
}
func (UnimplementedRagLlmServiceServer) HealthCheck(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRagLlmServiceServer) GenerateEmbedding(context.Context, *EmbeddingRequest) (*EmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateEmbedding not implemented")
}
func (UnimplementedRagLlmServiceServer) SearchSimilarDocuments(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchSimilarDocuments not implemented")
}
func (UnimplementedRagLlmServiceServer) GenerateAnswer(context.Context, *GenerateAnswerRequest) (*GenerateAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAnswer not implemented")
}
func (UnimplementedRagLlmServiceServer) mustEmbedUnimplementedRagLlmServiceServer() {}

// UnsafeRagLlmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagLlmServiceServer will
// result in compilation errors.
type UnsafeRagLlmServiceServer interface {
	mustEmbedUnimplementedRagLlmServiceServer()
}

func RegisterRagLlmServiceServer(s grpc.ServiceRegistrar, srv RagLlmServiceServer) {
	s.RegisterService(&RagLlmService_ServiceDesc, srv)
}

func _RagLlmService_DoSomething_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagllmServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagLlmServiceServer).DoSomething(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagLlmService_DoSomething_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagLlmServiceServer).DoSomething(ctx, req.(*RagllmServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagLlmService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagLlmServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagLlmService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagLlmServiceServer).HealthCheck(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagLlmService_GenerateEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagLlmServiceServer).GenerateEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagLlmService_GenerateEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagLlmServiceServer).GenerateEmbedding(ctx, req.(*EmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagLlmService_SearchSimilarDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagLlmServiceServer).SearchSimilarDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagLlmService_SearchSimilarDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagLlmServiceServer).SearchSimilarDocuments(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagLlmService_GenerateAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagLlmServiceServer).GenerateAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagLlmService_GenerateAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagLlmServiceServer).GenerateAnswer(ctx, req.(*GenerateAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagLlmService_ServiceDesc is the grpc.ServiceDesc for RagLlmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagLlmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ragllm_service.RagLlmService",
	HandlerType: (*RagLlmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoSomething",
			Handler:    _RagLlmService_DoSomething_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RagLlmService_HealthCheck_Handler,
		},
		{
			MethodName: "GenerateEmbedding",
			Handler:    _RagLlmService_GenerateEmbedding_Handler,
		},
		{
			MethodName: "SearchSimilarDocuments",
			Handler:    _RagLlmService_SearchSimilarDocuments_Handler,
		},
		{
			MethodName: "GenerateAnswer",
			Handler:    _RagLlmService_GenerateAnswer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ragllm_service.proto",
}
