# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flow.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nflow.proto\x12\x04\x66low\"/\n\x04\x46low\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x05nodes\x18\x02 \x03(\x0b\x32\n.flow.Node\"\xa8\x01\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12.\n\nparameters\x18\x04 \x03(\x0b\x32\x1a.flow.Node.ParametersEntry\x12\x15\n\rnext_node_ids\x18\x05 \x03(\t\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42=Z;github.com/milkyhoop/flow-executor/internal/proto/flow;flowb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/milkyhoop/flow-executor/internal/proto/flow;flow'
  _globals['_NODE_PARAMETERSENTRY']._loaded_options = None
  _globals['_NODE_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_FLOW']._serialized_start=20
  _globals['_FLOW']._serialized_end=67
  _globals['_NODE']._serialized_start=70
  _globals['_NODE']._serialized_end=238
  _globals['_NODE_PARAMETERSENTRY']._serialized_start=189
  _globals['_NODE_PARAMETERSENTRY']._serialized_end=238
# @@protoc_insertion_point(module_scope)
