# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business_parser.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62usiness_parser.proto\x12\x0f\x62usiness_parser\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n\x15\x43lassifyIntentRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"\xc5\x01\n\x16\x43lassifyIntentResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x15\n\rentities_json\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x11\n\treasoning\x18\x04 \x01(\t\x12\x12\n\nmodel_used\x18\x05 \x01(\t\x12\x1a\n\x12processing_time_ms\x18\x06 \x01(\x05\x12-\n\ttimestamp\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xb2\x01\n\x0e\x42usinessParser\x12\x61\n\x0e\x43lassifyIntent\x12&.business_parser.ClassifyIntentRequest\x1a\'.business_parser.ClassifyIntentResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business_parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFYINTENTREQUEST']._serialized_start=104
  _globals['_CLASSIFYINTENTREQUEST']._serialized_end=197
  _globals['_CLASSIFYINTENTRESPONSE']._serialized_start=200
  _globals['_CLASSIFYINTENTRESPONSE']._serialized_end=397
  _globals['_BUSINESSPARSER']._serialized_start=400
  _globals['_BUSINESSPARSER']._serialized_end=578
# @@protoc_insertion_point(module_scope)
