# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import conversation_manager_pb2 as conversation__manager__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in conversation_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class Complaint_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoSomething = channel.unary_unary(
                '/conversation_manager.Complaint_service/DoSomething',
                request_serializer=conversation__manager__pb2.Complaint_serviceRequest.SerializeToString,
                response_deserializer=conversation__manager__pb2.Complaint_serviceResponse.FromString,
                _registered_method=True)
        self.CreateComplaint = channel.unary_unary(
                '/conversation_manager.Complaint_service/CreateComplaint',
                request_serializer=conversation__manager__pb2.CreateComplaintRequest.SerializeToString,
                response_deserializer=conversation__manager__pb2.CreateComplaintResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/conversation_manager.Complaint_service/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class Complaint_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoSomething(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateComplaint(self, request, context):
        """✅ Baru ditambahkan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Complaint_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoSomething': grpc.unary_unary_rpc_method_handler(
                    servicer.DoSomething,
                    request_deserializer=conversation__manager__pb2.Complaint_serviceRequest.FromString,
                    response_serializer=conversation__manager__pb2.Complaint_serviceResponse.SerializeToString,
            ),
            'CreateComplaint': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateComplaint,
                    request_deserializer=conversation__manager__pb2.CreateComplaintRequest.FromString,
                    response_serializer=conversation__manager__pb2.CreateComplaintResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conversation_manager.Complaint_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Complaint_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoSomething(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation_manager.Complaint_service/DoSomething',
            conversation__manager__pb2.Complaint_serviceRequest.SerializeToString,
            conversation__manager__pb2.Complaint_serviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateComplaint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation_manager.Complaint_service/CreateComplaint',
            conversation__manager__pb2.CreateComplaintRequest.SerializeToString,
            conversation__manager__pb2.CreateComplaintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conversation_manager.Complaint_service/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
