# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: visualhoop-compiler.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'visualhoop-compiler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19visualhoop-compiler.proto\x12\x13visualhoop_compiler\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x0e\x43ompileRequest\x12\x11\n\tjson_path\x18\x01 \x01(\t\x12\x13\n\x0boutput_path\x18\x02 \x01(\t\"\"\n\x0f\x43ompileResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"G\n\x04\x46low\x12\x0e\n\x06intent\x18\x01 \x03(\t\x12/\n\x08\x65ntities\x18\x02 \x01(\x0b\x32\x1d.visualhoop_compiler.Entities\"\xc6\x01\n\x08\x45ntities\x12/\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32\x1d.visualhoop_compiler.Customer\x12@\n\x11order_transaction\x18\x02 \x01(\x0b\x32%.visualhoop_compiler.OrderTransaction\x12G\n\x15product_service_issue\x18\x03 \x01(\x0b\x32(.visualhoop_compiler.ProductServiceIssue\"3\n\x08\x43ustomer\x12\x15\n\rcustomer_name\x18\x01 \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\"I\n\x10OrderTransaction\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\titem_name\x18\x02 \x03(\t\x12\x10\n\x08quantity\x18\x03 \x03(\x05\"%\n\x13ProductServiceIssue\x12\x0e\n\x06reason\x18\x01 \x01(\t2\xb1\x01\n\x12VisualhoopCompiler\x12\\\n\x0f\x43ompileJsonToPb\x12#.visualhoop_compiler.CompileRequest\x1a$.visualhoop_compiler.CompileResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBZZXgithub.com/milkyhoop/milkyhoop/backend/services/visualhoop-compiler/internal/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'visualhoop_compiler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZXgithub.com/milkyhoop/milkyhoop/backend/services/visualhoop-compiler/internal/proto;proto'
  _globals['_COMPILEREQUEST']._serialized_start=79
  _globals['_COMPILEREQUEST']._serialized_end=135
  _globals['_COMPILERESPONSE']._serialized_start=137
  _globals['_COMPILERESPONSE']._serialized_end=171
  _globals['_FLOW']._serialized_start=173
  _globals['_FLOW']._serialized_end=244
  _globals['_ENTITIES']._serialized_start=247
  _globals['_ENTITIES']._serialized_end=445
  _globals['_CUSTOMER']._serialized_start=447
  _globals['_CUSTOMER']._serialized_end=498
  _globals['_ORDERTRANSACTION']._serialized_start=500
  _globals['_ORDERTRANSACTION']._serialized_end=573
  _globals['_PRODUCTSERVICEISSUE']._serialized_start=575
  _globals['_PRODUCTSERVICEISSUE']._serialized_end=612
  _globals['_VISUALHOOPCOMPILER']._serialized_start=615
  _globals['_VISUALHOOPCOMPILER']._serialized_end=792
# @@protoc_insertion_point(module_scope)
