"""
known_intents.py — Authoritative intent vocabulary for Milkyhoop chatbot gold-set.

Sources:
  1. Code grep: entity_extractor.py + direct_action_registry.py
     (pattern: (query|calc|create|update|delete|void|reverse)_[a-z0-9_]+)
  2. DB telemetry: SELECT DISTINCT final_intent FROM intent_decision_log
     (5 719 rows as of 2026-06-05)

Usage in later tasks:
  from tests.chat.goldset.known_intents import KNOWN_INTENTS
  assert dataset_row["expected_intent"] in KNOWN_INTENTS, f"Unknown label: {row['expected_intent']}"

Notes:
  - "ambiguous", "chitchat", "contextual_drill_down", "drilldown_table", "query",
    "reformat_as_table" are classifier-produced labels from DB telemetry only.
  - "query_gross_profit_projection" is in code (entity_extractor.py) but not yet
    seen in DB telemetry; dispatched via projection_engine which may bypass the log.
  - DB-only variants that appear to be older/alias names are included for completeness.
"""

KNOWN_INTENTS: set[str] = {
    # ── Calc (aggregate math, no LLM) ───────────────────────────────────────
    "calc_avg_harga_beli",
    "calc_avg_harga_jual",
    "calc_count_bank_accounts",
    "calc_count_bills_active",
    "calc_count_bills_outstanding",
    "calc_count_bom_active",
    "calc_count_customers_active",
    "calc_count_customers_inactive",
    "calc_count_expenses_month",
    "calc_count_expenses_this_month",
    "calc_count_invoices_outstanding",
    "calc_count_items_active",
    "calc_count_items_inactive",
    "calc_count_sales_invoices_active",
    "calc_count_vendors_active",
    "calc_count_vendors_inactive",
    "calc_count_work_centers",
    "calc_count_work_orders_active",
    "calc_count_work_orders_draft",
    "calc_profit_margin_per_item",
    "calc_rank_customers_by_ar",
    "calc_rank_expense_accounts",
    "calc_rank_items_by_price",
    "calc_rank_items_by_stock",
    "calc_rank_vendors_by_ap",
    "calc_rank_work_orders_by_quantity",
    "calc_sum_all_bank_balances",
    "calc_sum_ar",
    "calc_sum_bank_balance",
    "calc_sum_bills_outstanding",
    "calc_sum_expenses_this_month",
    "calc_sum_harga_beli",
    "calc_sum_harga_jual",
    "calc_sum_invoices_outstanding",
    "calc_sum_paid_this_month",
    "calc_sum_purchases_this_month",
    "calc_sum_received_this_month",
    "calc_sum_sales_this_month",
    "calc_sum_stok",
    "calc_top_selling_items",
    # ── Create (CRUD — write) ────────────────────────────────────────────────
    "create_account",
    "create_bank_account",
    "create_bank_transfer",
    "create_bill",
    "create_bill_payment",
    "create_bom",
    "create_category",
    "create_credit_note",
    "create_customer",
    "create_customer_deposit",
    "create_expense",
    "create_item",
    "create_journal_entry",
    "create_quote",
    "create_receive_payment",
    "create_sales_invoice",
    "create_sales_order",
    "create_stock_adjustment",
    "create_stock_transfer",
    "create_unit",
    "create_vendor",
    "create_vendor_credit",
    "create_vendor_deposit",
    "create_warehouse",
    "create_work_center",
    "create_work_order",
    # ── Update ───────────────────────────────────────────────────────────────
    "update_account",
    "update_bank_account",
    "update_bill",
    "update_customer",
    "update_item",
    "update_sales_invoice",
    "update_sales_order",
    "update_vendor",
    "update_warehouse",
    # ── Delete ───────────────────────────────────────────────────────────────
    "delete_bank_account",
    "delete_bill",
    "delete_customer",
    "delete_item",
    "delete_vendor",
    "delete_warehouse",
    # ── Void ────────────────────────────────────────────────────────────────
    "void_bank_transfer",
    "void_bill",
    "void_bill_payment",
    "void_credit_note",
    "void_customer_deposit",
    "void_expense",
    "void_reason",
    "void_receive_payment",
    "void_sales_invoice",
    "void_sales_order",
    "void_stock_adjustment",
    "void_vendor_credit",
    "void_vendor_deposit",
    "void_work_order",
    # ── Reverse ──────────────────────────────────────────────────────────────
    "reverse_journal",
    # ── Query (read — Gemini pipeline) ───────────────────────────────────────
    "query_account_detail",
    "query_account_ledger",
    "query_accounts_list",
    "query_action",
    "query_ap_aging",
    "query_ap_by_vendor",
    "query_ap_outstanding",
    "query_ar_aging",
    "query_ar_by_customer",
    "query_ar_invoices",
    "query_ar_outstanding",
    "query_balance_sheet",
    "query_bank_account_balance",
    "query_bank_account_detail",
    "query_bank_accounts_list",
    "query_bank_transactions",
    "query_bank_transactions_by_date",
    "query_bank_transfers_list",
    "query_bill_detail",
    "query_bill_payment_detail",
    "query_bill_payments_list",
    "query_bills_by_vendor",
    "query_bills_list",
    "query_bills_outstanding",
    "query_bills_overdue",
    "query_bills_summary",
    "query_bills_unpaid",
    "query_business_drivers",  # why-question contributing-facts (driver_deltas path)
    "query_bom_cost_breakdown",
    "query_bom_detail",
    "query_bom_list",
    "query_bom_materials_required",
    "query_cash_balance",
    "query_cash_flow",
    "query_cash_flow_projection",
    "query_cash_flow_trends",
    "query_categories_list",
    "query_credit_note_detail",
    "query_credit_notes_list",
    "query_credit_notes_summary",
    "query_customer_ar",
    "query_customer_deposits_list",
    "query_customer_detail",
    "query_customers_list",
    "query_customers_summary",
    "query_customers_with_overdue",
    "query_daily_transactions",
    "query_dashboard_summary",
    "query_expense_detail",
    "query_expense_summary",
    "query_expenses_by_account",
    "query_expenses_by_date_range",
    "query_expenses_list",
    "query_expenses_summary",
    "query_fg_receipts",
    "query_general_ledger",
    "query_gross_profit_projection",  # code only; projection_engine path
    "query_hutang_detail",
    "query_intent",
    "query_inventory_health",
    "query_inventory_summary",
    "query_invoice_summary",
    "query_item_activity",
    "query_item_batches",
    "query_item_detail",
    "query_item_journal",
    "query_item_related",
    "query_item_sales_summary",
    "query_item_stock_card",
    "query_item_transactions",
    "query_items_by_price",
    "query_items_by_stock",
    "query_items_expired",
    "query_items_expiring_soon",
    "query_items_inactive",
    "query_items_list",
    "query_items_low_stock",
    "query_items_margins",
    "query_items_no_stock",
    "query_items_quarantine",
    "query_items_search",
    "query_items_slow_moving",
    "query_items_stats",
    "query_items_summary",
    "query_items_top_products",
    "query_items_units",
    "query_journal_detail",
    "query_journals_list",
    "query_keys",
    "query_material_issues",
    "query_overdue_all",
    "query_params",
    "query_period_transactions",
    "query_periods",
    "query_piutang_detail",
    "query_production_active",
    "query_production_schedule",
    "query_profit_loss",
    "query_quote_detail",
    "query_quotes_list",
    "query_quotes_summary",
    "query_receive_payment_detail",
    "query_receive_payments_list",
    "query_reconciliation_status",
    "query_recurring_bills_list",
    "query_sales_daily",
    "query_sales_invoice_detail",
    "query_sales_invoices_list",
    "query_sales_invoices_overdue",
    "query_sales_invoices_summary",
    "query_sales_invoices_unpaid",
    "query_sales_today",
    "query_stock_adjustment_detail",
    "query_stock_adjustments",
    "query_stock_adjustments_summary",
    "query_stock_in_transit",
    "query_stock_transfers",
    "query_top_expenses",
    "query_trial_balance",
    "query_vendor_ap",
    "query_vendor_credit_detail",
    "query_vendor_credits_list",
    "query_vendor_credits_summary",
    "query_vendor_deposits_list",
    "query_vendor_detail",
    "query_vendors_list",
    "query_vendors_summary",
    "query_vendors_with_overdue",
    "query_warehouse_stock",
    "query_warehouse_stock_value",
    "query_warehouses",
    "query_work_center_list",
    "query_work_order_cost_analysis",
    "query_work_order_detail",
    "query_work_order_list",
    # ── Classifier-produced / meta labels (DB telemetry only) ───────────────
    "ambiguous",
    "chitchat",
    "contextual_drill_down",
    "drilldown_table",
    "query",  # generic fallback used by LLM router
    "reformat_as_table",
}
