# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import context_service_pb2 as context__service__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in context_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ContextServiceStub(object):
    """Context Resolution Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveReference = channel.unary_unary(
                '/context_service.ContextService/ResolveReference',
                request_serializer=context__service__pb2.ReferenceRequest.SerializeToString,
                response_deserializer=context__service__pb2.ReferenceResponse.FromString,
                _registered_method=True)
        self.StoreConversationTurn = channel.unary_unary(
                '/context_service.ContextService/StoreConversationTurn',
                request_serializer=context__service__pb2.ConversationTurnRequest.SerializeToString,
                response_deserializer=context__service__pb2.ConversationTurnResponse.FromString,
                _registered_method=True)
        self.GetProactiveData = channel.unary_unary(
                '/context_service.ContextService/GetProactiveData',
                request_serializer=context__service__pb2.ProactiveDataRequest.SerializeToString,
                response_deserializer=context__service__pb2.ProactiveDataResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/context_service.ContextService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=context__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class ContextServiceServicer(object):
    """Context Resolution Service
    """

    def ResolveReference(self, request, context):
        """Resolve references in user message
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreConversationTurn(self, request, context):
        """Store conversation turn for context tracking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProactiveData(self, request, context):
        """Get proactive business data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveReference': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveReference,
                    request_deserializer=context__service__pb2.ReferenceRequest.FromString,
                    response_serializer=context__service__pb2.ReferenceResponse.SerializeToString,
            ),
            'StoreConversationTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreConversationTurn,
                    request_deserializer=context__service__pb2.ConversationTurnRequest.FromString,
                    response_serializer=context__service__pb2.ConversationTurnResponse.SerializeToString,
            ),
            'GetProactiveData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProactiveData,
                    request_deserializer=context__service__pb2.ProactiveDataRequest.FromString,
                    response_serializer=context__service__pb2.ProactiveDataResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=context__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'context_service.ContextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContextService(object):
    """Context Resolution Service
    """

    @staticmethod
    def ResolveReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context_service.ContextService/ResolveReference',
            context__service__pb2.ReferenceRequest.SerializeToString,
            context__service__pb2.ReferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreConversationTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context_service.ContextService/StoreConversationTurn',
            context__service__pb2.ConversationTurnRequest.SerializeToString,
            context__service__pb2.ConversationTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProactiveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context_service.ContextService/GetProactiveData',
            context__service__pb2.ProactiveDataRequest.SerializeToString,
            context__service__pb2.ProactiveDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/context_service.ContextService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            context__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
