# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth/auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uth/auth.proto\x12\x0bprotos.auth\x1a\x1bgoogle/protobuf/empty.proto\"R\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\"\n\x0fUserInfoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"E\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"\x7f\n\rLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\x12\x12\n\nexpires_in\x18\x03 \x01(\x03\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x1f\n\x04role\x18\x05 \x01(\x0e\x32\x11.protos.auth.Role\"Q\n\x0eVerifyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x1f\n\x04role\x18\x03 \x01(\x0e\x32\x11.protos.auth.Role\"S\n\x10UserInfoResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x1f\n\x04role\x18\x03 \x01(\x0e\x32\x11.protos.auth.Role\"3\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t*<\n\x04Role\x12\x08\n\x04\x46REE\x10\x00\x12\x08\n\x04USER\x10\x01\x12\x0c\n\x08\x42USINESS\x10\x02\x12\x07\n\x03ORG\x10\x03\x12\t\n\x05\x41\x44MIN\x10\x04\x32\xee\x02\n\x0b\x41uthService\x12G\n\x08Register\x12\x1c.protos.auth.RegisterRequest\x1a\x1d.protos.auth.RegisterResponse\x12>\n\x05Login\x12\x19.protos.auth.LoginRequest\x1a\x1a.protos.auth.LoginResponse\x12\x46\n\x0bVerifyToken\x12\x1a.protos.auth.VerifyRequest\x1a\x1b.protos.auth.VerifyResponse\x12J\n\x0bGetUserInfo\x12\x1c.protos.auth.UserInfoRequest\x1a\x1d.protos.auth.UserInfoResponse\x12\x42\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1b.protos.auth.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=683
  _globals['_ROLE']._serialized_end=743
  _globals['_REGISTERREQUEST']._serialized_start=61
  _globals['_REGISTERREQUEST']._serialized_end=143
  _globals['_LOGINREQUEST']._serialized_start=145
  _globals['_LOGINREQUEST']._serialized_end=192
  _globals['_VERIFYREQUEST']._serialized_start=194
  _globals['_VERIFYREQUEST']._serialized_end=224
  _globals['_USERINFOREQUEST']._serialized_start=226
  _globals['_USERINFOREQUEST']._serialized_end=260
  _globals['_REGISTERRESPONSE']._serialized_start=262
  _globals['_REGISTERRESPONSE']._serialized_end=331
  _globals['_LOGINRESPONSE']._serialized_start=333
  _globals['_LOGINRESPONSE']._serialized_end=460
  _globals['_VERIFYRESPONSE']._serialized_start=462
  _globals['_VERIFYRESPONSE']._serialized_end=543
  _globals['_USERINFORESPONSE']._serialized_start=545
  _globals['_USERINFORESPONSE']._serialized_end=628
  _globals['_HEALTHRESPONSE']._serialized_start=630
  _globals['_HEALTHRESPONSE']._serialized_end=681
  _globals['_AUTHSERVICE']._serialized_start=746
  _globals['_AUTHSERVICE']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
