# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import ragllm_service_pb2 as ragllm__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ragllm_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagLlmServiceStub(object):
    """===== SERVICE DEFINITION (AFTER ALL MESSAGES) =====
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ragllm_service.RagLlmService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DoSomething = channel.unary_unary(
                '/ragllm_service.RagLlmService/DoSomething',
                request_serializer=ragllm__service__pb2.Ragllm_serviceRequest.SerializeToString,
                response_deserializer=ragllm__service__pb2.Ragllm_serviceResponse.FromString,
                _registered_method=True)
        self.GenerateEmbedding = channel.unary_unary(
                '/ragllm_service.RagLlmService/GenerateEmbedding',
                request_serializer=ragllm__service__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=ragllm__service__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.SearchSimilarDocuments = channel.unary_unary(
                '/ragllm_service.RagLlmService/SearchSimilarDocuments',
                request_serializer=ragllm__service__pb2.SearchRequest.SerializeToString,
                response_deserializer=ragllm__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GenerateAnswer = channel.unary_unary(
                '/ragllm_service.RagLlmService/GenerateAnswer',
                request_serializer=ragllm__service__pb2.GenerateAnswerRequest.SerializeToString,
                response_deserializer=ragllm__service__pb2.GenerateAnswerResponse.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_unary(
                '/ragllm_service.RagLlmService/Synthesize',
                request_serializer=ragllm__service__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=ragllm__service__pb2.SynthesizeResponse.FromString,
                _registered_method=True)


class RagLlmServiceServicer(object):
    """===== SERVICE DEFINITION (AFTER ALL MESSAGES) =====
    """

    def HealthCheck(self, request, context):
        """Health and utility methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoSomething(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbedding(self, request, context):
        """Embedding and search methods  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSimilarDocuments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAnswer(self, request, context):
        """Primary response generation methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagLlmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DoSomething': grpc.unary_unary_rpc_method_handler(
                    servicer.DoSomething,
                    request_deserializer=ragllm__service__pb2.Ragllm_serviceRequest.FromString,
                    response_serializer=ragllm__service__pb2.Ragllm_serviceResponse.SerializeToString,
            ),
            'GenerateEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbedding,
                    request_deserializer=ragllm__service__pb2.EmbeddingRequest.FromString,
                    response_serializer=ragllm__service__pb2.EmbeddingResponse.SerializeToString,
            ),
            'SearchSimilarDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSimilarDocuments,
                    request_deserializer=ragllm__service__pb2.SearchRequest.FromString,
                    response_serializer=ragllm__service__pb2.SearchResponse.SerializeToString,
            ),
            'GenerateAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAnswer,
                    request_deserializer=ragllm__service__pb2.GenerateAnswerRequest.FromString,
                    response_serializer=ragllm__service__pb2.GenerateAnswerResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=ragllm__service__pb2.SynthesizeRequest.FromString,
                    response_serializer=ragllm__service__pb2.SynthesizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ragllm_service.RagLlmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ragllm_service.RagLlmService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagLlmService(object):
    """===== SERVICE DEFINITION (AFTER ALL MESSAGES) =====
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragllm_service.RagLlmService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DoSomething(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragllm_service.RagLlmService/DoSomething',
            ragllm__service__pb2.Ragllm_serviceRequest.SerializeToString,
            ragllm__service__pb2.Ragllm_serviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragllm_service.RagLlmService/GenerateEmbedding',
            ragllm__service__pb2.EmbeddingRequest.SerializeToString,
            ragllm__service__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSimilarDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragllm_service.RagLlmService/SearchSimilarDocuments',
            ragllm__service__pb2.SearchRequest.SerializeToString,
            ragllm__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragllm_service.RagLlmService/GenerateAnswer',
            ragllm__service__pb2.GenerateAnswerRequest.SerializeToString,
            ragllm__service__pb2.GenerateAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ragllm_service.RagLlmService/Synthesize',
            ragllm__service__pb2.SynthesizeRequest.SerializeToString,
            ragllm__service__pb2.SynthesizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
