# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment/payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment/payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment/payment.proto\x12\x07payment\"7\n\x14\x43reateInvoiceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\";\n\x15\x43reateInvoiceResponse\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"C\n\x15\x43onfirmPaymentRequest\x12\x12\n\ninvoice_id\x18\x01 \x01(\t\x12\x16\n\x0epayment_method\x18\x02 \x01(\t\"A\n\x16\x43onfirmPaymentResponse\x12\x17\n\x0f\x63onfirmation_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xb3\x01\n\x0ePaymentService\x12N\n\rCreateInvoice\x12\x1d.payment.CreateInvoiceRequest\x1a\x1e.payment.CreateInvoiceResponse\x12Q\n\x0e\x43onfirmPayment\x12\x1e.payment.ConfirmPaymentRequest\x1a\x1f.payment.ConfirmPaymentResponseBCZAgithub.com/milkyhoop/payment-service/internal/delivery/pb/paymentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment.payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/milkyhoop/payment-service/internal/delivery/pb/payment'
  _globals['_CREATEINVOICEREQUEST']._serialized_start=34
  _globals['_CREATEINVOICEREQUEST']._serialized_end=89
  _globals['_CREATEINVOICERESPONSE']._serialized_start=91
  _globals['_CREATEINVOICERESPONSE']._serialized_end=150
  _globals['_CONFIRMPAYMENTREQUEST']._serialized_start=152
  _globals['_CONFIRMPAYMENTREQUEST']._serialized_end=219
  _globals['_CONFIRMPAYMENTRESPONSE']._serialized_start=221
  _globals['_CONFIRMPAYMENTRESPONSE']._serialized_end=286
  _globals['_PAYMENTSERVICE']._serialized_start=289
  _globals['_PAYMENTSERVICE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
