# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversation_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'conversation_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63onversation_service.proto\x12\x14\x63onversation_service\x1a\x1bgoogle/protobuf/empty.proto\"=\n\x1b\x43onversation_serviceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\">\n\x1c\x43onversation_serviceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\xcb\x01\n\x14\x43onversation_service\x12t\n\x0b\x44oSomething\x12\x31.conversation_service.Conversation_serviceRequest\x1a\x32.conversation_service.Conversation_serviceResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBUZSgithub.com/milkyhoop/template-service-golang/internal/delivery/pb/template;templateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZSgithub.com/milkyhoop/template-service-golang/internal/delivery/pb/template;template'
  _globals['_CONVERSATION_SERVICEREQUEST']._serialized_start=81
  _globals['_CONVERSATION_SERVICEREQUEST']._serialized_end=142
  _globals['_CONVERSATION_SERVICERESPONSE']._serialized_start=144
  _globals['_CONVERSATION_SERVICERESPONSE']._serialized_end=206
  _globals['_CONVERSATION_SERVICE']._serialized_start=209
  _globals['_CONVERSATION_SERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
