# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class Role(StrEnum):
    FREE = 'FREE'
    BUSINESS = 'BUSINESS'
    PRO = 'PRO'
    CORPORATE = 'CORPORATE'
    ADMIN = 'ADMIN'

class MediaType(StrEnum):
    IMAGE = 'IMAGE'
    VIDEO = 'VIDEO'
