from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Account',
    'Session',
    'RefreshToken',
    'UserSecurity',
    'UserProfile',
    'VerificationToken',
    'ChatMessage',
    'UserBusiness',
    'UserLocations',
    'UserFinance',
    'UserSubscriptions',
    'Plans',
    'UserAISettings',
    'UserMedia',
    'Tenant',
    'Order',
    'Memory',
    'RagDocument',
    'AuditLog',
    'TransaksiHarian',
    'ItemTransaksi',
    'HppBreakdown',
    'InventoryImpact',
    'ItemInventory',
    'Products',
    'Supplier',
    'Persediaan',
    'Outbox',
    'TenantRule',
    'TaxInfo',
    'BaganAkun',
    'JurnalEntry',
    'JurnalDetail',
    'QRLoginToken',
    'UserDevice',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'tenant': 'Tenant',
        'accounts': 'Account',
        'sessions': 'Session',
        'profile': 'UserProfile',
        'security': 'UserSecurity',
        'business': 'UserBusiness',
        'locations': 'UserLocations',
        'finance': 'UserFinance',
        'subscriptions': 'UserSubscriptions',
        'aiSettings': 'UserAISettings',
        'media': 'UserMedia',
        'auditLogs': 'AuditLog',
        'transaksiCreated': 'TransaksiHarian',
        'transaksiApproved': 'TransaksiHarian',
        'refreshTokens': 'RefreshToken',
        'chatMessages': 'ChatMessage',
        'devices': 'UserDevice',
    },
    'Account': {
        'user': 'User',
    },
    'Session': {
        'user': 'User',
    },
    'RefreshToken': {
        'user': 'User',
        'tenant': 'Tenant',
    },
    'UserSecurity': {
        'user': 'User',
    },
    'UserProfile': {
        'user': 'User',
    },
    'VerificationToken': {
    },
    'ChatMessage': {
        'user': 'User',
        'tenant': 'Tenant',
    },
    'UserBusiness': {
        'user': 'User',
    },
    'UserLocations': {
        'user': 'User',
    },
    'UserFinance': {
        'user': 'User',
    },
    'UserSubscriptions': {
        'user': 'User',
        'plan': 'Plans',
    },
    'Plans': {
        'subscriptions': 'UserSubscriptions',
    },
    'UserAISettings': {
        'user': 'User',
    },
    'UserMedia': {
        'user': 'User',
    },
    'Tenant': {
        'users': 'User',
        'transaksiHarian': 'TransaksiHarian',
        'taxInfo': 'TaxInfo',
        'products': 'Products',
        'suppliers': 'Supplier',
        'persediaan': 'Persediaan',
        'baganAkun': 'BaganAkun',
        'jurnalEntries': 'JurnalEntry',
        'refreshTokens': 'RefreshToken',
        'chatMessages': 'ChatMessage',
        'tenantRules': 'TenantRule',
        'devices': 'UserDevice',
    },
    'Order': {
    },
    'Memory': {
    },
    'RagDocument': {
    },
    'AuditLog': {
        'user': 'User',
    },
    'TransaksiHarian': {
        'tenant': 'Tenant',
        'creator': 'User',
        'approver': 'User',
        'outbox': 'Outbox',
        'items': 'ItemTransaksi',
        'hpp': 'HppBreakdown',
        'inventoryImpact': 'InventoryImpact',
        'jurnalEntries': 'JurnalEntry',
    },
    'ItemTransaksi': {
        'transaksi': 'TransaksiHarian',
    },
    'HppBreakdown': {
        'transaksi': 'TransaksiHarian',
    },
    'InventoryImpact': {
        'transaksi': 'TransaksiHarian',
        'itemsInventory': 'ItemInventory',
    },
    'ItemInventory': {
        'inventoryImpact': 'InventoryImpact',
    },
    'Products': {
        'tenant': 'Tenant',
        'persediaan': 'Persediaan',
    },
    'Supplier': {
        'tenant': 'Tenant',
    },
    'Persediaan': {
        'tenant': 'Tenant',
        'product': 'Products',
    },
    'Outbox': {
        'transaksi': 'TransaksiHarian',
    },
    'TenantRule': {
        'tenant': 'Tenant',
    },
    'TaxInfo': {
        'tenant': 'Tenant',
    },
    'BaganAkun': {
        'tenant': 'Tenant',
        'parent': 'BaganAkun',
        'children': 'BaganAkun',
        'jurnalDetails': 'JurnalDetail',
    },
    'JurnalEntry': {
        'tenant': 'Tenant',
        'transaksi': 'TransaksiHarian',
        'details': 'JurnalDetail',
    },
    'JurnalDetail': {
        'jurnalEntry': 'JurnalEntry',
        'akun': 'BaganAkun',
    },
    'QRLoginToken': {
    },
    'UserDevice': {
        'user': 'User',
        'tenant': 'Tenant',
    },
}

# fmt: on
