# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_service.proto\x12\x0fpayment_service\x1a\x1bgoogle/protobuf/empty.proto\"8\n\x16Payment_serviceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x01(\t\"9\n\x17Payment_serviceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\xb1\x01\n\x0ePaymentService\x12`\n\x0b\x44oSomething\x12\'.payment_service.Payment_serviceRequest\x1a(.payment_service.Payment_serviceResponse\x12=\n\x0bHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.EmptyBUZSgithub.com/milkyhoop/template-service-golang/internal/delivery/pb/template;templateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZSgithub.com/milkyhoop/template-service-golang/internal/delivery/pb/template;template'
  _globals['_PAYMENT_SERVICEREQUEST']._serialized_start=71
  _globals['_PAYMENT_SERVICEREQUEST']._serialized_end=127
  _globals['_PAYMENT_SERVICERESPONSE']._serialized_start=129
  _globals['_PAYMENT_SERVICERESPONSE']._serialized_end=186
  _globals['_PAYMENTSERVICE']._serialized_start=189
  _globals['_PAYMENTSERVICE']._serialized_end=366
# @@protoc_insertion_point(module_scope)
