# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseAccount(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Account']] = 'Account'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AccountActions[_PrismaModelT]':
        from .client import get_client

        return actions.AccountActions[_PrismaModelT](client or get_client(), cls)


class BaseSession(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Session']] = 'Session'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SessionActions[_PrismaModelT]':
        from .client import get_client

        return actions.SessionActions[_PrismaModelT](client or get_client(), cls)


class BaseUserSecurity(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserSecurity']] = 'UserSecurity'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserSecurityActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserSecurityActions[_PrismaModelT](client or get_client(), cls)


class BaseUserProfile(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserProfile']] = 'UserProfile'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserProfileActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserProfileActions[_PrismaModelT](client or get_client(), cls)


class BaseVerificationToken(_PrismaModel):
    __prisma_model__: ClassVar[Literal['VerificationToken']] = 'VerificationToken'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.VerificationTokenActions[_PrismaModelT]':
        from .client import get_client

        return actions.VerificationTokenActions[_PrismaModelT](client or get_client(), cls)


class Basemessages(_PrismaModel):
    __prisma_model__: ClassVar[Literal['messages']] = 'messages'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.messagesActions[_PrismaModelT]':
        from .client import get_client

        return actions.messagesActions[_PrismaModelT](client or get_client(), cls)


class BaseUserBusiness(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserBusiness']] = 'UserBusiness'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserBusinessActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserBusinessActions[_PrismaModelT](client or get_client(), cls)


class BaseUserLocations(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserLocations']] = 'UserLocations'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserLocationsActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserLocationsActions[_PrismaModelT](client or get_client(), cls)


class BaseUserFinance(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserFinance']] = 'UserFinance'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserFinanceActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserFinanceActions[_PrismaModelT](client or get_client(), cls)


class BaseUserSubscriptions(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserSubscriptions']] = 'UserSubscriptions'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserSubscriptionsActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserSubscriptionsActions[_PrismaModelT](client or get_client(), cls)


class BasePlans(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Plans']] = 'Plans'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PlansActions[_PrismaModelT]':
        from .client import get_client

        return actions.PlansActions[_PrismaModelT](client or get_client(), cls)


class BaseUserAISettings(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserAISettings']] = 'UserAISettings'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserAISettingsActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserAISettingsActions[_PrismaModelT](client or get_client(), cls)


class BaseUserMedia(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserMedia']] = 'UserMedia'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserMediaActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserMediaActions[_PrismaModelT](client or get_client(), cls)


class BaseTenant(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Tenant']] = 'Tenant'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TenantActions[_PrismaModelT]':
        from .client import get_client

        return actions.TenantActions[_PrismaModelT](client or get_client(), cls)


class BaseOrder(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Order']] = 'Order'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.OrderActions[_PrismaModelT]':
        from .client import get_client

        return actions.OrderActions[_PrismaModelT](client or get_client(), cls)


class BaseMemory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Memory']] = 'Memory'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MemoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.MemoryActions[_PrismaModelT](client or get_client(), cls)


class BaseRagDocument(_PrismaModel):
    __prisma_model__: ClassVar[Literal['RagDocument']] = 'RagDocument'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.RagDocumentActions[_PrismaModelT]':
        from .client import get_client

        return actions.RagDocumentActions[_PrismaModelT](client or get_client(), cls)


class BaseAuditLog(_PrismaModel):
    __prisma_model__: ClassVar[Literal['AuditLog']] = 'AuditLog'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.AuditLogActions[_PrismaModelT]':
        from .client import get_client

        return actions.AuditLogActions[_PrismaModelT](client or get_client(), cls)


class BaseTransaksiHarian(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TransaksiHarian']] = 'TransaksiHarian'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TransaksiHarianActions[_PrismaModelT]':
        from .client import get_client

        return actions.TransaksiHarianActions[_PrismaModelT](client or get_client(), cls)


class BaseItemTransaksi(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ItemTransaksi']] = 'ItemTransaksi'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ItemTransaksiActions[_PrismaModelT]':
        from .client import get_client

        return actions.ItemTransaksiActions[_PrismaModelT](client or get_client(), cls)


class BaseHppBreakdown(_PrismaModel):
    __prisma_model__: ClassVar[Literal['HppBreakdown']] = 'HppBreakdown'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.HppBreakdownActions[_PrismaModelT]':
        from .client import get_client

        return actions.HppBreakdownActions[_PrismaModelT](client or get_client(), cls)


class BaseInventoryImpact(_PrismaModel):
    __prisma_model__: ClassVar[Literal['InventoryImpact']] = 'InventoryImpact'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.InventoryImpactActions[_PrismaModelT]':
        from .client import get_client

        return actions.InventoryImpactActions[_PrismaModelT](client or get_client(), cls)


class BaseItemInventory(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ItemInventory']] = 'ItemInventory'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ItemInventoryActions[_PrismaModelT]':
        from .client import get_client

        return actions.ItemInventoryActions[_PrismaModelT](client or get_client(), cls)


class BasePersediaan(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Persediaan']] = 'Persediaan'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.PersediaanActions[_PrismaModelT]':
        from .client import get_client

        return actions.PersediaanActions[_PrismaModelT](client or get_client(), cls)


class BaseOutbox(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Outbox']] = 'Outbox'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.OutboxActions[_PrismaModelT]':
        from .client import get_client

        return actions.OutboxActions[_PrismaModelT](client or get_client(), cls)


class BaseTaxInfo(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TaxInfo']] = 'TaxInfo'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TaxInfoActions[_PrismaModelT]':
        from .client import get_client

        return actions.TaxInfoActions[_PrismaModelT](client or get_client(), cls)


class BaseBaganAkun(_PrismaModel):
    __prisma_model__: ClassVar[Literal['BaganAkun']] = 'BaganAkun'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.BaganAkunActions[_PrismaModelT]':
        from .client import get_client

        return actions.BaganAkunActions[_PrismaModelT](client or get_client(), cls)


class BaseJurnalEntry(_PrismaModel):
    __prisma_model__: ClassVar[Literal['JurnalEntry']] = 'JurnalEntry'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.JurnalEntryActions[_PrismaModelT]':
        from .client import get_client

        return actions.JurnalEntryActions[_PrismaModelT](client or get_client(), cls)


class BaseJurnalDetail(_PrismaModel):
    __prisma_model__: ClassVar[Literal['JurnalDetail']] = 'JurnalDetail'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.JurnalDetailActions[_PrismaModelT]':
        from .client import get_client

        return actions.JurnalDetailActions[_PrismaModelT](client or get_client(), cls)


