# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import action_plan_pb2 as action__plan__pb2
import action_validator_pb2 as action__validator__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in action_validator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ActionValidatorServiceStub(object):
    """=============================
    ActionValidatorService
    Validates action plans before execution.
    Performs business rule checks, permission checks,
    and dry-run accounting previews.
    =============================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateAction = channel.unary_unary(
                '/milkyhoop.actions.ActionValidatorService/ValidateAction',
                request_serializer=action__validator__pb2.ValidateActionRequest.SerializeToString,
                response_deserializer=action__validator__pb2.ValidateActionResponse.FromString,
                _registered_method=True)
        self.DryRunAction = channel.unary_unary(
                '/milkyhoop.actions.ActionValidatorService/DryRunAction',
                request_serializer=action__validator__pb2.DryRunActionRequest.SerializeToString,
                response_deserializer=action__validator__pb2.DryRunActionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/milkyhoop.actions.ActionValidatorService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=action__plan__pb2.HealthResponse.FromString,
                _registered_method=True)


class ActionValidatorServiceServicer(object):
    """=============================
    ActionValidatorService
    Validates action plans before execution.
    Performs business rule checks, permission checks,
    and dry-run accounting previews.
    =============================

    """

    def ValidateAction(self, request, context):
        """Validate an action plan against all business rules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DryRunAction(self, request, context):
        """Perform a dry-run to preview journal entries without persisting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionValidatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAction,
                    request_deserializer=action__validator__pb2.ValidateActionRequest.FromString,
                    response_serializer=action__validator__pb2.ValidateActionResponse.SerializeToString,
            ),
            'DryRunAction': grpc.unary_unary_rpc_method_handler(
                    servicer.DryRunAction,
                    request_deserializer=action__validator__pb2.DryRunActionRequest.FromString,
                    response_serializer=action__validator__pb2.DryRunActionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=action__plan__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'milkyhoop.actions.ActionValidatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ActionValidatorService(object):
    """=============================
    ActionValidatorService
    Validates action plans before execution.
    Performs business rule checks, permission checks,
    and dry-run accounting previews.
    =============================

    """

    @staticmethod
    def ValidateAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.ActionValidatorService/ValidateAction',
            action__validator__pb2.ValidateActionRequest.SerializeToString,
            action__validator__pb2.ValidateActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DryRunAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.ActionValidatorService/DryRunAction',
            action__validator__pb2.DryRunActionRequest.SerializeToString,
            action__validator__pb2.DryRunActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.ActionValidatorService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            action__plan__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
