# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import action_executor_pb2 as action__executor__pb2
import action_plan_pb2 as action__plan__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in action_executor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ActionExecutorServiceStub(object):
    """=============================
    ActionExecutorService
    Executes validated action plans with two-phase commit:
    1. PrepareAction - creates a pending action with preview, returns confirmation token
    2. ExecuteAction - executes after user confirmation
    Also supports cancellation and status queries.
    =============================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrepareAction = channel.unary_unary(
                '/milkyhoop.actions.ActionExecutorService/PrepareAction',
                request_serializer=action__executor__pb2.PrepareActionRequest.SerializeToString,
                response_deserializer=action__executor__pb2.PrepareActionResponse.FromString,
                _registered_method=True)
        self.ExecuteAction = channel.unary_unary(
                '/milkyhoop.actions.ActionExecutorService/ExecuteAction',
                request_serializer=action__executor__pb2.ExecuteActionRequest.SerializeToString,
                response_deserializer=action__executor__pb2.ExecuteActionResponse.FromString,
                _registered_method=True)
        self.CancelAction = channel.unary_unary(
                '/milkyhoop.actions.ActionExecutorService/CancelAction',
                request_serializer=action__executor__pb2.CancelActionRequest.SerializeToString,
                response_deserializer=action__executor__pb2.CancelActionResponse.FromString,
                _registered_method=True)
        self.GetActionStatus = channel.unary_unary(
                '/milkyhoop.actions.ActionExecutorService/GetActionStatus',
                request_serializer=action__executor__pb2.GetActionStatusRequest.SerializeToString,
                response_deserializer=action__executor__pb2.GetActionStatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/milkyhoop.actions.ActionExecutorService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=action__plan__pb2.HealthResponse.FromString,
                _registered_method=True)


class ActionExecutorServiceServicer(object):
    """=============================
    ActionExecutorService
    Executes validated action plans with two-phase commit:
    1. PrepareAction - creates a pending action with preview, returns confirmation token
    2. ExecuteAction - executes after user confirmation
    Also supports cancellation and status queries.
    =============================

    """

    def PrepareAction(self, request, context):
        """Prepare an action for execution (creates pending state, returns preview)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAction(self, request, context):
        """Execute a previously prepared action (requires confirmation token)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAction(self, request, context):
        """Cancel a pending action before execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActionStatus(self, request, context):
        """Query the current status of an action
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionExecutorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrepareAction': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareAction,
                    request_deserializer=action__executor__pb2.PrepareActionRequest.FromString,
                    response_serializer=action__executor__pb2.PrepareActionResponse.SerializeToString,
            ),
            'ExecuteAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=action__executor__pb2.ExecuteActionRequest.FromString,
                    response_serializer=action__executor__pb2.ExecuteActionResponse.SerializeToString,
            ),
            'CancelAction': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAction,
                    request_deserializer=action__executor__pb2.CancelActionRequest.FromString,
                    response_serializer=action__executor__pb2.CancelActionResponse.SerializeToString,
            ),
            'GetActionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActionStatus,
                    request_deserializer=action__executor__pb2.GetActionStatusRequest.FromString,
                    response_serializer=action__executor__pb2.GetActionStatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=action__plan__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'milkyhoop.actions.ActionExecutorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ActionExecutorService(object):
    """=============================
    ActionExecutorService
    Executes validated action plans with two-phase commit:
    1. PrepareAction - creates a pending action with preview, returns confirmation token
    2. ExecuteAction - executes after user confirmation
    Also supports cancellation and status queries.
    =============================

    """

    @staticmethod
    def PrepareAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.ActionExecutorService/PrepareAction',
            action__executor__pb2.PrepareActionRequest.SerializeToString,
            action__executor__pb2.PrepareActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.ActionExecutorService/ExecuteAction',
            action__executor__pb2.ExecuteActionRequest.SerializeToString,
            action__executor__pb2.ExecuteActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.ActionExecutorService/CancelAction',
            action__executor__pb2.CancelActionRequest.SerializeToString,
            action__executor__pb2.CancelActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.ActionExecutorService/GetActionStatus',
            action__executor__pb2.GetActionStatusRequest.SerializeToString,
            action__executor__pb2.GetActionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.ActionExecutorService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            action__plan__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
