# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import action_plan_pb2 as action__plan__pb2
import audit_pb2 as audit__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AuditServiceStub(object):
    """=============================
    AuditService
    Immutable audit logging for all actions in the Agentic Accounting system.
    Every stage of an action's lifecycle is recorded:
    intent parsing, validation, confirmation, execution, and journal posting.
    =============================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogEvent = channel.unary_unary(
                '/milkyhoop.actions.AuditService/LogEvent',
                request_serializer=audit__pb2.LogEventRequest.SerializeToString,
                response_deserializer=audit__pb2.LogEventResponse.FromString,
                _registered_method=True)
        self.GetAuditTrail = channel.unary_unary(
                '/milkyhoop.actions.AuditService/GetAuditTrail',
                request_serializer=audit__pb2.GetAuditTrailRequest.SerializeToString,
                response_deserializer=audit__pb2.GetAuditTrailResponse.FromString,
                _registered_method=True)
        self.GetEntityHistory = channel.unary_unary(
                '/milkyhoop.actions.AuditService/GetEntityHistory',
                request_serializer=audit__pb2.GetEntityHistoryRequest.SerializeToString,
                response_deserializer=audit__pb2.GetEntityHistoryResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/milkyhoop.actions.AuditService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=action__plan__pb2.HealthResponse.FromString,
                _registered_method=True)


class AuditServiceServicer(object):
    """=============================
    AuditService
    Immutable audit logging for all actions in the Agentic Accounting system.
    Every stage of an action's lifecycle is recorded:
    intent parsing, validation, confirmation, execution, and journal posting.
    =============================

    """

    def LogEvent(self, request, context):
        """Log a single audit event
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditTrail(self, request, context):
        """Query the audit trail for a specific action (by action_id)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityHistory(self, request, context):
        """Query the full history of a specific entity (by entity_id)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogEvent,
                    request_deserializer=audit__pb2.LogEventRequest.FromString,
                    response_serializer=audit__pb2.LogEventResponse.SerializeToString,
            ),
            'GetAuditTrail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditTrail,
                    request_deserializer=audit__pb2.GetAuditTrailRequest.FromString,
                    response_serializer=audit__pb2.GetAuditTrailResponse.SerializeToString,
            ),
            'GetEntityHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityHistory,
                    request_deserializer=audit__pb2.GetEntityHistoryRequest.FromString,
                    response_serializer=audit__pb2.GetEntityHistoryResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=action__plan__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'milkyhoop.actions.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """=============================
    AuditService
    Immutable audit logging for all actions in the Agentic Accounting system.
    Every stage of an action's lifecycle is recorded:
    intent parsing, validation, confirmation, execution, and journal posting.
    =============================

    """

    @staticmethod
    def LogEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.AuditService/LogEvent',
            audit__pb2.LogEventRequest.SerializeToString,
            audit__pb2.LogEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditTrail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.AuditService/GetAuditTrail',
            audit__pb2.GetAuditTrailRequest.SerializeToString,
            audit__pb2.GetAuditTrailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntityHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.AuditService/GetEntityHistory',
            audit__pb2.GetEntityHistoryRequest.SerializeToString,
            audit__pb2.GetEntityHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/milkyhoop.actions.AuditService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            action__plan__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
