# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: google/health.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'google/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13google/health.proto\x12\x0egrpc.health.v1\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xa9\x01\n\x13HealthCheckResponse\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32\x31.grpc.health.v1.HealthCheckResponse.ServingStatus\"O\n\rServingStatus\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x12\x13\n\x0fSERVICE_UNKNOWN\x10\x03\"\x13\n\x11HealthListRequest\"\xae\x01\n\x12HealthListResponse\x12\x42\n\x08statuses\x18\x01 \x03(\x0b\x32\x30.grpc.health.v1.HealthListResponse.StatusesEntry\x1aT\n\rStatusesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.grpc.health.v1.HealthCheckResponse:\x02\x38\x01\x32\xfd\x01\n\x06Health\x12P\n\x05\x43heck\x12\".grpc.health.v1.HealthCheckRequest\x1a#.grpc.health.v1.HealthCheckResponse\x12M\n\x04List\x12!.grpc.health.v1.HealthListRequest\x1a\".grpc.health.v1.HealthListResponse\x12R\n\x05Watch\x12\".grpc.health.v1.HealthCheckRequest\x1a#.grpc.health.v1.HealthCheckResponse0\x01\x42p\n\x11io.grpc.health.v1B\x0bHealthProtoP\x01Z,google.golang.org/grpc/health/grpc_health_v1\xa2\x02\x0cGrpcHealthV1\xaa\x02\x0eGrpc.Health.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021io.grpc.health.v1B\013HealthProtoP\001Z,google.golang.org/grpc/health/grpc_health_v1\242\002\014GrpcHealthV1\252\002\016Grpc.Health.V1'
  _globals['_HEALTHLISTRESPONSE_STATUSESENTRY']._loaded_options = None
  _globals['_HEALTHLISTRESPONSE_STATUSESENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHCHECKREQUEST']._serialized_start=39
  _globals['_HEALTHCHECKREQUEST']._serialized_end=76
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=79
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=248
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_start=169
  _globals['_HEALTHCHECKRESPONSE_SERVINGSTATUS']._serialized_end=248
  _globals['_HEALTHLISTREQUEST']._serialized_start=250
  _globals['_HEALTHLISTREQUEST']._serialized_end=269
  _globals['_HEALTHLISTRESPONSE']._serialized_start=272
  _globals['_HEALTHLISTRESPONSE']._serialized_end=446
  _globals['_HEALTHLISTRESPONSE_STATUSESENTRY']._serialized_start=362
  _globals['_HEALTHLISTRESPONSE_STATUSESENTRY']._serialized_end=446
  _globals['_HEALTH']._serialized_start=449
  _globals['_HEALTH']._serialized_end=702
# @@protoc_insertion_point(module_scope)
