from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Account',
    'Session',
    'UserSecurity',
    'UserProfile',
    'VerificationToken',
    'messages',
    'UserBusiness',
    'UserLocations',
    'UserFinance',
    'UserSubscriptions',
    'Plans',
    'UserAISettings',
    'UserMedia',
    'Tenant',
    'Order',
    'Memory',
    'RagDocument',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'accounts': 'Account',
        'sessions': 'Session',
        'profile': 'UserProfile',
        'security': 'UserSecurity',
        'business': 'UserBusiness',
        'locations': 'UserLocations',
        'finance': 'UserFinance',
        'subscriptions': 'UserSubscriptions',
        'aiSettings': 'UserAISettings',
        'media': 'UserMedia',
    },
    'Account': {
        'user': 'User',
    },
    'Session': {
        'user': 'User',
    },
    'UserSecurity': {
        'user': 'User',
    },
    'UserProfile': {
        'user': 'User',
    },
    'VerificationToken': {
    },
    'messages': {
    },
    'UserBusiness': {
        'user': 'User',
    },
    'UserLocations': {
        'user': 'User',
    },
    'UserFinance': {
        'user': 'User',
    },
    'UserSubscriptions': {
        'user': 'User',
        'plan': 'Plans',
    },
    'Plans': {
        'subscriptions': 'UserSubscriptions',
    },
    'UserAISettings': {
        'user': 'User',
    },
    'UserMedia': {
        'user': 'User',
    },
    'Tenant': {
    },
    'Order': {
    },
    'Memory': {
    },
    'RagDocument': {
    },
}

# fmt: on