#ENC[AES256_GCM,data:CMssgMQ2BeQAycDcDbSq4+tXtdll+pvA5k7LsoI=,iv:USQKe11IkLz+/L8TbM1vSXtsFHIT8SUFCRwG8AmFJyw=,tag:S5xD+lw0JvrFE9uEEN22ag==,type:comment]
#ENC[AES256_GCM,data:6B2ZBXXrD4Xsr8wmuGMnZOlFMMIgxoUXJkPMH5ghN2MKwCNm3m4=,iv:DKvve5trDDMsH7f+UlkCsPHUT6R/0ngxeL9L2LgEJxI=,tag:fxgeay+c2UOxrsMszabN/A==,type:comment]
database:
    postgres_password: ENC[AES256_GCM,data:+U4tkVW5fR0l5HirBq5O0iw105TQ3VFJypKb13UanRU=,iv:j+NN4CpDBwk45//uhQXWYOo/y+5g1jBZjo9rCX3KsRs=,tag:ia0x23PvCXXHcBHNJNMMwQ==,type:str]
    db_password: ENC[AES256_GCM,data:7qjPAXJniBwsLM19,iv:UGZ8o6IJss9aF7bHxyUD/yg89ahlWWeXT6o60wj5Dg4=,tag:jUc894fV3q577IyRVsngWA==,type:str]
    database_url: ENC[AES256_GCM,data:6UZo70dILQ91PzEzbyeltS0FipHxG534y4tgSzJ99AD7COEGEinGNM288s0bUxk0u2osAnEM458=,iv:EMSu51YaXhne1fOZU8BwkMrYCkNsYN3D2kD/IxQ804o=,tag:4Zk8Lx3f3VaQfkKhN8Gocg==,type:str]
redis:
    password: ENC[AES256_GCM,data:cb/MZvQ8ODD6qoDqpYcFUC9B1+paMD91/pcTIkEPCmI=,iv:V0v/D8O5bUh03Q42E9RhRY3ctZ+K0PtBW0ybzGbsChc=,tag:zV8Cyu0U1zO4vbxgahsvrg==,type:str]
auth:
    jwt_secret: ENC[AES256_GCM,data:MrF0verxILiAiGA5MYQYJp0zfbRd3NRtxo/S/GykJopUThekK4a9FXSvmuV6DdxV5WfkOFG/KL4qewaHdn7tCQARZW7ITPXLNRQWwdBztXWqqkhXP+KljuKL+tQOaU7T2izpDhWP4Y65fYCK3ZBv/B4hG6+zogc8NXjWN1xZBRM=,iv:3513LTa/xbj0ZHOQm3w03exMlLJ8/IXuX7i7WqGELQE=,tag:2Mos9RY2ZfEfL5fYADm9xw==,type:str]
    internal_api_key: ENC[AES256_GCM,data:4LtpfBzJdA3pnv85t2HFvxuY0emxedHv4wa5sGwd5wnA4eX8KVbKO+jyG6vIAhMe9ooHsMpCNMOVYyDSLtDcUQ==,iv:jUvVsuEt2RaZ6THxVzbyRCI6EZrzloXEurvQJRPJYpI=,tag:wTAx2N8tfluC1VlBCGG+9A==,type:str]
    grpc_token: ENC[AES256_GCM,data:PHYSzHYbYPA78hfLU9qp99/Kdy2FDKssZHgGSC3euK2gs4/YPFKPGMLMEgJrKNtfhsglOeafkHbV1g==,iv:yMya/CzWwXOYrEirffPIZbBmNutiPqRfSjdGM5P2ISY=,tag:2+u8lPadM4LajlwWtkVBSg==,type:str]
    secret_key: ENC[AES256_GCM,data:lFanO6+Ox2BUriY5z2MkXQjHiEM8djQ0T8Xsq8h4bLRLqNH/F7IDBd/lyGPoU2xVJFh6/S32C9kb+Mn0yvZIx29y+v6+H120n+/RoTA=,iv:eF94t6rPuVSE8Rh0K5w/D8xGPv4e/en2ZHiJJ5+svMs=,tag:FOTeVp99o5sOSR0DunhSkw==,type:str]
    nextauth_secret: ENC[AES256_GCM,data:M1zgLGwRA47azojBIZcEuUWzQyt/tnOhQW5jhOs91gicjMoA/kwpxlb3RNKVg9PE,iv:S/clyl7mR3aZ5MBxQJ5DYJeA9YcdxvZWDPEhKMCDKOc=,tag:YsYdbPSuPXEfj9zKjcZnuA==,type:str]
external_apis:
    openai_api_key: ENC[AES256_GCM,data:0wBKl0ARMoZUxLaQs9fCgunY1AZxZ+4dkYXDMjvM5DUIBW/hADD6kYGQob2BdnfOT+N4iMJBAAV8HW9lwhjzus9HF4SR97Mzo1HBo3bOttfxQ8F2G2y+Nlf9s9vHvVMEe7O0URqC/4UMh5IcWbY3Or/7fjNHb+J9UVOfC5W/feiQZzwt/HwgdD+hT17Ok8EP4Omg1e9Gwnp8vAMjrwh8Iv7i/90=,iv:+I/Gq0VHLGgcoKYc9s7I0MThVCjKZg64e2g8Eaxnmqg=,tag:Dcx1ssuXzcxYanQvhkx4pg==,type:str]
    google_client_secret: ENC[AES256_GCM,data:EOgz2xQ4gIoKiV+vTx5k72tZwh6AhN7Smr+c8Z9Qfj6a3rGv2I30,iv:wT05+b3lVdhnohYc65OA9H6O+xJgnBkArv+PD1wo7n8=,tag:LBLBo9HG9mtQmBG29hYmKw==,type:str]
    turnstile_secret_key: ENC[AES256_GCM,data:RRJqO3z382uAUAYR5FBobGr9fEL22OQnojktfSngwDz7Xfw=,iv:I0p9mivQWeII3tf3TXOoNqbZ4/15Dm7AcaA1tduFXXE=,tag:eBQtpuXzyfrO3RQBe496ew==,type:str]
backup:
    restic_password: ENC[AES256_GCM,data:oNp9O1JJKaItDNHss1TTZTZx8teffG4C3N4HNWXDWWANzbhplC9EyGZwIc0=,iv:2YPaB8S2mt5pP/4rZ85mJUVo1kDGzlQJk0R86s5kbLw=,tag:RlN+RJpBB6S4hKH6BETycw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ha44p0556qhxmhqt46c6jj8xat0n0kwulesr4a3dngulv9vsmq6qnkwvgn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMkdCUmpka1AxNFZwRFkw
            aXc1SlUwN1hQSjRkOVFiNTNnV1ZWREtVRjA4ClpSV0NZc3dOQmFDZ2pZVHRsK3hJ
            eS9Idmpoc1JmWm5VS0NGQW12cFZ1bXMKLS0tIGp4WGdYQXNwaHFPZ05ma1NyNkpC
            TUY4YWtBcldMZEhYZjNQWTRCTTNpTjQKU3OZ42UFSodvRSbwj/dxbMxPOJgDXfqC
            bJCKIizfQWZZ1N0b3VFj3QRF2mdLWXouttiIZ1grGjcprB7tGk3GQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T06:55:29Z"
    mac: ENC[AES256_GCM,data:1NPiCCITWR5QGvl0uV7JcNQUTuUUkRxHoy25diTFz1Ub6CLbUzuQhIkLXsZn1HGcs/3CASNIMCm+3957tuBbw7g33+9H4fxtiq8NSXVaRMg4603IdJqzwPqIk+zQUnHRoEFho/cWSSh2pzDx63VuLZBHZ4/NqeiOyWWiVg62B3g=,iv:EY0DUkB5jaZDH2h5Nu3eOupdYbpNKZyNMipw1lmgFqE=,tag:aCZUJgqm6Tu5bKMWL0xGNg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
